//! AUTOGENERATED FOR Axiom Verge 2 - MODIFICATIONS WILL BE LOST

#![allow(unused)]
#![allow(non_snake_case)]

use analyzer::context::Ctx;
use analyzer::world::*;
use analyzer::*;
use libaxiom_verge2::context::{enums, flags, Context, Status};
use libaxiom_verge2::graph::{self, *};
use libaxiom_verge2::items::Item;

fn shared_setup() -> (graph::World, Context) {
    let mut world = graph::World::new();
    let mut ctx = Context::default();
    ctx.cbits1.insert(flags::ContextBits1::ICE_AXE);
    ctx.cbits1.insert(flags::ContextBits1::AMASHILAMA);
    ctx.cbits1.insert(flags::ContextBits1::BOOMERANG);
    ctx.cbits1.insert(flags::ContextBits1::LEDGE_GRAB);
    ctx.save = SpotId::Ebih__Base_Camp__Save_Point;

    (world, ctx)
}

#[test]
fn can_reach_Ebih__Ebih_East__Corner() {
    let (mut world, mut ctx) = shared_setup();

    expect_any_route!(
        &world,
        ctx,
        SpotId::Ebih__Base_Camp__Save_Point,
        SpotId::Ebih__Ebih_East__Corner
    );
}
#[test]
fn can_obtain_Infect() {
    let (mut world, mut ctx) = shared_setup();

    expect_obtainable!(
        &world,
        ctx,
        SpotId::Ebih__Base_Camp__Save_Point,
        Item::Infect
    );
}
#[test]
fn context_flasks_1_can_obtain_Melee_Damage() {
    let (mut world, mut ctx) = shared_setup();
    ctx.flasks = 1;

    expect_obtainable!(
        &world,
        ctx,
        SpotId::Ebih__Base_Camp__Save_Point,
        Item::Melee_Damage
    );
}
#[test]
fn start_Ebih__Ebih_East__East_Ledge_can_obtain_Remote_Drone() {
    let (mut world, mut ctx) = shared_setup();

    expect_obtainable!(
        &world,
        ctx,
        SpotId::Ebih__Ebih_East__East_Ledge,
        Item::Remote_Drone
    );
}
#[test]
fn start_Ebih__Drone_Room__East_4_context_mode_drone_indra_Ebih__Drone_Room__Tree_can_reach_Ebih__Grid_25_2_6__Pit(
) {
    let (mut world, mut ctx) = shared_setup();
    ctx.mode = enums::Mode::Drone;
    ctx.indra = SpotId::Ebih__Drone_Room__Tree;

    expect_any_route!(
        &world,
        ctx,
        SpotId::Ebih__Drone_Room__East_4,
        SpotId::Ebih__Grid_25_2_6__Pit
    );
}
#[test]
fn start_Ebih__Drone_Room__West_6_with_Infect__Remote_Drone_can_activate_Ebih__Drone_Room__Moving_Platform__Throw_Drone(
) {
    let (mut world, mut ctx) = shared_setup();
    ctx.infect = 1;
    ctx.cbits1.insert(flags::ContextBits1::REMOTE_DRONE);

    expect_action_accessible!(
        &world,
        ctx,
        SpotId::Ebih__Drone_Room__West_6,
        ActionId::Ebih__Drone_Room__Moving_Platform__Throw_Drone
    );
}
#[test]
fn start_Ebih__Ebih_East__Corner_with_Infect_can_activate_Ebih__Ebih_East__Lower_Moving_Platform__Activate_Lift(
) {
    let (mut world, mut ctx) = shared_setup();
    ctx.infect = 1;

    expect_action_accessible!(
        &world,
        ctx,
        SpotId::Ebih__Ebih_East__Corner,
        ActionId::Ebih__Ebih_East__Lower_Moving_Platform__Activate_Lift
    );
}
#[test]
fn start_Ebih__Ebih_East__West_8_with_Infect_can_activate_Ebih__Ebih_East__Moving_Platform__Activate_Ride(
) {
    let (mut world, mut ctx) = shared_setup();
    ctx.infect = 1;

    expect_action_accessible!(
        &world,
        ctx,
        SpotId::Ebih__Ebih_East__West_8,
        ActionId::Ebih__Ebih_East__Moving_Platform__Activate_Ride
    );
}
#[test]
fn start_Ebih__Ebih_East__West_8_with_Infect_eventually_reaches_Ebih__Ebih_East__Middle_Platform() {
    let (mut world, mut ctx) = shared_setup();
    ctx.infect = 1;

    expect_eventually_reaches!(
        &world,
        ctx,
        SpotId::Ebih__Ebih_East__West_8,
        SpotId::Ebih__Ebih_East__Middle_Platform
    );
}
#[test]
fn start_Ebih__Ebih_East__Middle_Platform_can_reach_Ebih__Ebih_East__East_Ledge() {
    let (mut world, mut ctx) = shared_setup();

    expect_any_route!(
        &world,
        ctx,
        SpotId::Ebih__Ebih_East__Middle_Platform,
        SpotId::Ebih__Ebih_East__East_Ledge
    );
}
#[test]
fn start_Ebih__Drone_Room__Portal_with_Infect_requires_context_save_Ebih__Ebih_West__Upper_Save_to_reach_Ebih__Drone_Room__Moving_Platform(
) {
    let (mut world, mut ctx) = shared_setup();
    ctx.infect = 1;

    let mut ctx2 = ctx.clone();
    ctx2.save = SpotId::Ebih__Ebih_West__Upper_Save;

    expect_no_route!(
        &world,
        ctx,
        SpotId::Ebih__Drone_Room__Portal,
        SpotId::Ebih__Drone_Room__Moving_Platform
    );
    expect_any_route!(
        &world,
        ctx2,
        SpotId::Ebih__Drone_Room__Portal,
        SpotId::Ebih__Drone_Room__Moving_Platform
    );
}
#[test]
fn start_Glacier__Vertical_Room__Peak_can_access_Glacier__Vertical_Room__Peak__Flask() {
    let (mut world, mut ctx) = shared_setup();

    expect_accessible!(
        &world,
        ctx,
        SpotId::Glacier__Vertical_Room__Peak,
        LocationId::Glacier__Vertical_Room__Peak__Flask
    );
}
#[test]
fn start_Menu__Upgrade_Menu__Physiology_context_last_Ebih__Ebih_East__West_8_visited_Glacier__Vertical_Room__Peak__Flask_can_reach_Ebih__Ebih_East__Corner(
) {
    let (mut world, mut ctx) = shared_setup();
    ctx.last = SpotId::Ebih__Ebih_East__West_8;
    ctx.visit(LocationId::Glacier__Vertical_Room__Peak__Flask);

    expect_any_route!(
        &world,
        ctx,
        SpotId::Menu__Upgrade_Menu__Physiology,
        SpotId::Ebih__Ebih_East__Corner
    );
}
#[test]
fn start_Glacier__Vertical_Room__Peak_with_Flask_context_flasks_1_visited_Glacier__Vertical_Room__Peak__Flask_can_access_Menu__Upgrade_Menu__Physiology__Health_Upgrade_1(
) {
    let (mut world, mut ctx) = shared_setup();
    ctx.flask = 1;
    ctx.flasks = 1;
    ctx.visit(LocationId::Glacier__Vertical_Room__Peak__Flask);

    expect_accessible!(
        &world,
        ctx,
        SpotId::Glacier__Vertical_Room__Peak,
        LocationId::Menu__Upgrade_Menu__Physiology__Health_Upgrade_1
    );
}
#[test]
fn start_Ebih__Ebih_East__Middle_Platform_with_Infect__Remote_Drone_can_access_Ebih__Grid_25_10_12__Hidden_Bush__Behind_Bush(
) {
    let (mut world, mut ctx) = shared_setup();
    ctx.infect = 1;
    ctx.cbits1.insert(flags::ContextBits1::REMOTE_DRONE);

    expect_accessible!(
        &world,
        ctx,
        SpotId::Ebih__Ebih_East__Middle_Platform,
        LocationId::Ebih__Grid_25_10_12__Hidden_Bush__Behind_Bush
    );
}
#[test]
fn start_Ebih__Grid_25_10_12__East_12_with_Infect__Remote_Drone_eventually_accesses_Ebih__Grid_25_10_12__Hidden_Bush__Behind_Bush(
) {
    let (mut world, mut ctx) = shared_setup();
    ctx.infect = 1;
    ctx.cbits1.insert(flags::ContextBits1::REMOTE_DRONE);

    expect_eventually_accesses!(
        &world,
        ctx,
        SpotId::Ebih__Grid_25_10_12__East_12,
        LocationId::Ebih__Grid_25_10_12__Hidden_Bush__Behind_Bush
    );
}
