//! AUTOGENERATED FOR Axiom Verge 2 - MODIFICATIONS WILL BE LOST

use analyzer::unittest::*;
use libaxiom_verge2::context::Context;
use libaxiom_verge2::graph;
use std::path::PathBuf;

fn main() {
    let mut dir = PathBuf::from(file!());
    dir.pop();
    let mut routedir = dir.clone();
    routedir.pop();
    routedir.push("routes");
    run_all_tests_in_dir::<graph::World, Context>(&dir, Some(&routedir));
}
