//! AUTOGENERATED FOR Axiom Verge 2 - MODIFICATIONS WILL BE LOST

use analyzer::unittest::*;
use libaxiom_verge2::context::Context;
use libaxiom_verge2::graph::World;
use std::path::Path;

fn main() {
    let dir = Path::new("tests");
    let routedir = Path::new("routes");
    let pb = Path::new("settings/log4unittest.yml");
    if pb.exists() {
        log4rs::init_file(pb, Default::default()).unwrap();
    }
    run_all_tests_in_dir::<World, Context>(dir, Some(&routedir));
}
