[package]
name = "analyzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-map = "*"
lru = "*"
plotlib = "0.5.1"
rmp-serde = "*"
rustc-hash = "*"
serde = { version = "1.0", features = ["derive", "rc"] }
sort_by_derive = "0.1.10"
yaml-rust = "*"
