//! AUTOGENERATED FOR sample - DO NOT MODIFY
//!
//! Context (game state).

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

use crate::context::*;
use crate::items::Item;
use crate::prices::Currency;
use analyzer::context::Ctx;
use analyzer::world;
use enum_map::{enum_map, EnumMap};
use std::fmt;

#[derive(Debug, PartialEq, Eq, Copy, Clone, enum_map::Enum)]
pub enum RegionId {
    Deku_Tree,
    KF,
    Kak,
}
impl fmt::Display for RegionId {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            RegionId::Deku_Tree => write!(f, "{}", "Deku Tree"),
            RegionId::KF => write!(f, "{}", "Kokiri Forest"),
            RegionId::Kak => write!(f, "{}", "Kakariko Village"),
        }
    }
}

#[derive(Debug, PartialEq, Eq, Copy, Clone, enum_map::Enum)]
pub enum AreaId {
    Deku_Tree__Lobby,
    Deku_Tree__Floor_2,
    Deku_Tree__Scrub_Room,
    Deku_Tree__Slingshot_Room,
    Deku_Tree__Slingshot_Upper,
    Deku_Tree__Floor_3,
    Deku_Tree__Compass_Room,
    Deku_Tree__Basement_1,
    Deku_Tree__Back_Room,
    Deku_Tree__Skull_Room,
    Deku_Tree__Basement_Ledge,
    Deku_Tree__Basement_2,
    Deku_Tree__Boss_Room,
    KF__Links_House,
    KF__Kokiri_Village,
    KF__Boulder_Maze,
    KF__Baba_Corridor,
    KF__Outside_Deku_Tree,
    KF__Midos_House,
    KF__Knowitall_House,
    KF__Shop,
    Kak__Spider_House,
}
impl fmt::Display for AreaId {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            AreaId::Deku_Tree__Lobby => write!(f, "{}", "Deku Tree > Lobby"),
            AreaId::Deku_Tree__Floor_2 => write!(f, "{}", "Deku Tree > Floor 2"),
            AreaId::Deku_Tree__Scrub_Room => write!(f, "{}", "Deku Tree > Scrub Room"),
            AreaId::Deku_Tree__Slingshot_Room => write!(f, "{}", "Deku Tree > Slingshot Room"),
            AreaId::Deku_Tree__Slingshot_Upper => write!(f, "{}", "Deku Tree > Slingshot Upper"),
            AreaId::Deku_Tree__Floor_3 => write!(f, "{}", "Deku Tree > Floor 3"),
            AreaId::Deku_Tree__Compass_Room => write!(f, "{}", "Deku Tree > Compass Room"),
            AreaId::Deku_Tree__Basement_1 => write!(f, "{}", "Deku Tree > Basement 1"),
            AreaId::Deku_Tree__Back_Room => write!(f, "{}", "Deku Tree > Back Room"),
            AreaId::Deku_Tree__Skull_Room => write!(f, "{}", "Deku Tree > Skull Room"),
            AreaId::Deku_Tree__Basement_Ledge => write!(f, "{}", "Deku Tree > Basement Ledge"),
            AreaId::Deku_Tree__Basement_2 => write!(f, "{}", "Deku Tree > Basement 2"),
            AreaId::Deku_Tree__Boss_Room => write!(f, "{}", "Deku Tree > Boss Room"),
            AreaId::KF__Links_House => write!(f, "{}", "KF > Link's House"),
            AreaId::KF__Kokiri_Village => write!(f, "{}", "KF > Kokiri Village"),
            AreaId::KF__Boulder_Maze => write!(f, "{}", "KF > Boulder Maze"),
            AreaId::KF__Baba_Corridor => write!(f, "{}", "KF > Baba Corridor"),
            AreaId::KF__Outside_Deku_Tree => write!(f, "{}", "KF > Outside Deku Tree"),
            AreaId::KF__Midos_House => write!(f, "{}", "KF > Mido's House"),
            AreaId::KF__Knowitall_House => write!(f, "{}", "KF > Know-it-all House"),
            AreaId::KF__Shop => write!(f, "{}", "KF > Shop"),
            AreaId::Kak__Spider_House => write!(f, "{}", "Kak > Spider House"),
        }
    }
}

#[derive(Debug, PartialEq, Eq, Copy, Clone, enum_map::Enum, Default)]
pub enum SpotId {
    #[default]
    None,
    Deku_Tree__Lobby__Entry,
    Deku_Tree__Lobby__Center,
    Deku_Tree__Lobby__Vines,
    Deku_Tree__Floor_2__Lower,
    Deku_Tree__Floor_2__Vines,
    Deku_Tree__Floor_2__Slingshot_Door,
    Deku_Tree__Scrub_Room__Entry,
    Deku_Tree__Scrub_Room__Rear,
    Deku_Tree__Slingshot_Room__Entry,
    Deku_Tree__Slingshot_Room__Slingshot,
    Deku_Tree__Slingshot_Upper__Ledge,
    Deku_Tree__Floor_3__Climb,
    Deku_Tree__Floor_3__Door,
    Deku_Tree__Compass_Room__Entry,
    Deku_Tree__Compass_Room__Compass,
    Deku_Tree__Compass_Room__Ledge,
    Deku_Tree__Basement_1__Center,
    Deku_Tree__Basement_1__Corner,
    Deku_Tree__Basement_1__South_Door,
    Deku_Tree__Back_Room__South,
    Deku_Tree__Back_Room__Northwest,
    Deku_Tree__Back_Room__East,
    Deku_Tree__Skull_Room__Entry,
    Deku_Tree__Basement_Ledge__Block,
    Deku_Tree__Basement_Ledge__Web,
    Deku_Tree__Basement_2__Pool,
    Deku_Tree__Basement_2__Boss_Door,
    Deku_Tree__Boss_Room__Entry,
    Deku_Tree__Boss_Room__Arena,
    KF__Links_House__Start_Point,
    KF__Links_House__Entry,
    KF__Kokiri_Village__Links_Porch,
    KF__Kokiri_Village__Midos_Porch,
    KF__Kokiri_Village__Knowitall_Porch,
    KF__Kokiri_Village__Training_Center,
    KF__Kokiri_Village__Shop_Porch,
    KF__Kokiri_Village__Sarias_Porch,
    KF__Kokiri_Village__Midos_Guardpost,
    KF__Boulder_Maze__Entry,
    KF__Boulder_Maze__Reward,
    KF__Baba_Corridor__Village_Side,
    KF__Baba_Corridor__Deku_Babas,
    KF__Baba_Corridor__Tree_Side,
    KF__Outside_Deku_Tree__Entry,
    KF__Outside_Deku_Tree__Left,
    KF__Outside_Deku_Tree__Right,
    KF__Outside_Deku_Tree__Mouth,
    KF__Midos_House__Entry,
    KF__Knowitall_House__Entry,
    KF__Shop__Entry,
    Kak__Spider_House__Entry,
}
impl fmt::Display for SpotId {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            SpotId::None => write!(f, "{}", "None"),
            SpotId::Deku_Tree__Lobby__Entry => write!(f, "{}", "Deku Tree > Lobby > Entry"),
            SpotId::Deku_Tree__Lobby__Center => write!(f, "{}", "Deku Tree > Lobby > Center"),
            SpotId::Deku_Tree__Lobby__Vines => write!(f, "{}", "Deku Tree > Lobby > Vines"),
            SpotId::Deku_Tree__Floor_2__Lower => write!(f, "{}", "Deku Tree > Floor 2 > Lower"),
            SpotId::Deku_Tree__Floor_2__Vines => write!(f, "{}", "Deku Tree > Floor 2 > Vines"),
            SpotId::Deku_Tree__Floor_2__Slingshot_Door => {
                write!(f, "{}", "Deku Tree > Floor 2 > Slingshot Door")
            }
            SpotId::Deku_Tree__Scrub_Room__Entry => {
                write!(f, "{}", "Deku Tree > Scrub Room > Entry")
            }
            SpotId::Deku_Tree__Scrub_Room__Rear => write!(f, "{}", "Deku Tree > Scrub Room > Rear"),
            SpotId::Deku_Tree__Slingshot_Room__Entry => {
                write!(f, "{}", "Deku Tree > Slingshot Room > Entry")
            }
            SpotId::Deku_Tree__Slingshot_Room__Slingshot => {
                write!(f, "{}", "Deku Tree > Slingshot Room > Slingshot")
            }
            SpotId::Deku_Tree__Slingshot_Upper__Ledge => {
                write!(f, "{}", "Deku Tree > Slingshot Upper > Ledge")
            }
            SpotId::Deku_Tree__Floor_3__Climb => write!(f, "{}", "Deku Tree > Floor 3 > Climb"),
            SpotId::Deku_Tree__Floor_3__Door => write!(f, "{}", "Deku Tree > Floor 3 > Door"),
            SpotId::Deku_Tree__Compass_Room__Entry => {
                write!(f, "{}", "Deku Tree > Compass Room > Entry")
            }
            SpotId::Deku_Tree__Compass_Room__Compass => {
                write!(f, "{}", "Deku Tree > Compass Room > Compass")
            }
            SpotId::Deku_Tree__Compass_Room__Ledge => {
                write!(f, "{}", "Deku Tree > Compass Room > Ledge")
            }
            SpotId::Deku_Tree__Basement_1__Center => {
                write!(f, "{}", "Deku Tree > Basement 1 > Center")
            }
            SpotId::Deku_Tree__Basement_1__Corner => {
                write!(f, "{}", "Deku Tree > Basement 1 > Corner")
            }
            SpotId::Deku_Tree__Basement_1__South_Door => {
                write!(f, "{}", "Deku Tree > Basement 1 > South Door")
            }
            SpotId::Deku_Tree__Back_Room__South => write!(f, "{}", "Deku Tree > Back Room > South"),
            SpotId::Deku_Tree__Back_Room__Northwest => {
                write!(f, "{}", "Deku Tree > Back Room > Northwest")
            }
            SpotId::Deku_Tree__Back_Room__East => write!(f, "{}", "Deku Tree > Back Room > East"),
            SpotId::Deku_Tree__Skull_Room__Entry => {
                write!(f, "{}", "Deku Tree > Skull Room > Entry")
            }
            SpotId::Deku_Tree__Basement_Ledge__Block => {
                write!(f, "{}", "Deku Tree > Basement Ledge > Block")
            }
            SpotId::Deku_Tree__Basement_Ledge__Web => {
                write!(f, "{}", "Deku Tree > Basement Ledge > Web")
            }
            SpotId::Deku_Tree__Basement_2__Pool => write!(f, "{}", "Deku Tree > Basement 2 > Pool"),
            SpotId::Deku_Tree__Basement_2__Boss_Door => {
                write!(f, "{}", "Deku Tree > Basement 2 > Boss Door")
            }
            SpotId::Deku_Tree__Boss_Room__Entry => write!(f, "{}", "Deku Tree > Boss Room > Entry"),
            SpotId::Deku_Tree__Boss_Room__Arena => write!(f, "{}", "Deku Tree > Boss Room > Arena"),
            SpotId::KF__Links_House__Start_Point => {
                write!(f, "{}", "KF > Link's House > Start Point")
            }
            SpotId::KF__Links_House__Entry => write!(f, "{}", "KF > Link's House > Entry"),
            SpotId::KF__Kokiri_Village__Links_Porch => {
                write!(f, "{}", "KF > Kokiri Village > Link's Porch")
            }
            SpotId::KF__Kokiri_Village__Midos_Porch => {
                write!(f, "{}", "KF > Kokiri Village > Mido's Porch")
            }
            SpotId::KF__Kokiri_Village__Knowitall_Porch => {
                write!(f, "{}", "KF > Kokiri Village > Know-it-all Porch")
            }
            SpotId::KF__Kokiri_Village__Training_Center => {
                write!(f, "{}", "KF > Kokiri Village > Training Center")
            }
            SpotId::KF__Kokiri_Village__Shop_Porch => {
                write!(f, "{}", "KF > Kokiri Village > Shop Porch")
            }
            SpotId::KF__Kokiri_Village__Sarias_Porch => {
                write!(f, "{}", "KF > Kokiri Village > Saria's Porch")
            }
            SpotId::KF__Kokiri_Village__Midos_Guardpost => {
                write!(f, "{}", "KF > Kokiri Village > Mido's Guardpost")
            }
            SpotId::KF__Boulder_Maze__Entry => write!(f, "{}", "KF > Boulder Maze > Entry"),
            SpotId::KF__Boulder_Maze__Reward => write!(f, "{}", "KF > Boulder Maze > Reward"),
            SpotId::KF__Baba_Corridor__Village_Side => {
                write!(f, "{}", "KF > Baba Corridor > Village Side")
            }
            SpotId::KF__Baba_Corridor__Deku_Babas => {
                write!(f, "{}", "KF > Baba Corridor > Deku Babas")
            }
            SpotId::KF__Baba_Corridor__Tree_Side => {
                write!(f, "{}", "KF > Baba Corridor > Tree Side")
            }
            SpotId::KF__Outside_Deku_Tree__Entry => {
                write!(f, "{}", "KF > Outside Deku Tree > Entry")
            }
            SpotId::KF__Outside_Deku_Tree__Left => write!(f, "{}", "KF > Outside Deku Tree > Left"),
            SpotId::KF__Outside_Deku_Tree__Right => {
                write!(f, "{}", "KF > Outside Deku Tree > Right")
            }
            SpotId::KF__Outside_Deku_Tree__Mouth => {
                write!(f, "{}", "KF > Outside Deku Tree > Mouth")
            }
            SpotId::KF__Midos_House__Entry => write!(f, "{}", "KF > Mido's House > Entry"),
            SpotId::KF__Knowitall_House__Entry => write!(f, "{}", "KF > Know-it-all House > Entry"),
            SpotId::KF__Shop__Entry => write!(f, "{}", "KF > Shop > Entry"),
            SpotId::Kak__Spider_House__Entry => write!(f, "{}", "Kak > Spider House > Entry"),
        }
    }
}

#[derive(Debug, PartialEq, Eq, Copy, Clone, enum_map::Enum)]
pub enum LocationId {
    Deku_Tree__Lobby__Center__Deku_Baba_Sticks,
    Deku_Tree__Lobby__Center__Deku_Baby_Nuts,
    Deku_Tree__Lobby__Center__Web,
    Deku_Tree__Floor_2__Vines__Map_Chest,
    Deku_Tree__Scrub_Room__Entry__Scrub,
    Deku_Tree__Slingshot_Room__Slingshot__Chest,
    Deku_Tree__Slingshot_Upper__Ledge__Chest,
    Deku_Tree__Floor_3__Door__Break_Web,
    Deku_Tree__Compass_Room__Entry__Burn_Web,
    Deku_Tree__Compass_Room__Compass__Chest,
    Deku_Tree__Compass_Room__Ledge__Chest,
    Deku_Tree__Compass_Room__Ledge__GS,
    Deku_Tree__Basement_1__Center__Vines_GS,
    Deku_Tree__Basement_1__Corner__Switch,
    Deku_Tree__Basement_1__Corner__Chest,
    Deku_Tree__Basement_1__Corner__Gate_GS,
    Deku_Tree__Basement_1__Corner__Burn_Basement_Web,
    Deku_Tree__Back_Room__Northwest__Burn_Web,
    Deku_Tree__Back_Room__Northwest__Break_Wall,
    Deku_Tree__Skull_Room__Entry__GS,
    Deku_Tree__Basement_Ledge__Block__Push_Block,
    Deku_Tree__Basement_Ledge__Web__Burn_Web,
    Deku_Tree__Basement_2__Boss_Door__Scrubs,
    Deku_Tree__Boss_Room__Arena__Gohma,
    Deku_Tree__Boss_Room__Arena__Gohma_Quick_Kill,
    Deku_Tree__Boss_Room__Arena__Gohma_Heart,
    Deku_Tree__Boss_Room__Arena__Blue_Warp,
    KF__Kokiri_Village__Midos_Guardpost__Show_Mido,
    KF__Boulder_Maze__Reward__Chest,
    KF__Baba_Corridor__Deku_Babas__Sticks,
    KF__Baba_Corridor__Deku_Babas__Nuts,
    KF__Outside_Deku_Tree__Left__Gossip_Stone,
    KF__Outside_Deku_Tree__Right__Gossip_Stone,
    KF__Midos_House__Entry__Top_Left_Chest,
    KF__Midos_House__Entry__Top_Right_Chest,
    KF__Midos_House__Entry__Bottom_Left_Chest,
    KF__Midos_House__Entry__Bottom_Right_Chest,
    KF__Shop__Entry__Blue_Rupee,
    KF__Shop__Entry__Item_1,
    KF__Shop__Entry__Item_2,
    KF__Shop__Entry__Item_3,
    KF__Shop__Entry__Item_4,
    KF__Shop__Entry__Item_5,
    KF__Shop__Entry__Item_6,
    KF__Shop__Entry__Item_7,
    KF__Shop__Entry__Item_8,
    Kak__Spider_House__Entry__Skulls_10,
}
impl fmt::Display for LocationId {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            LocationId::Deku_Tree__Lobby__Center__Deku_Baba_Sticks => {
                write!(f, "{}", "Deku Tree > Lobby > Center Deku Baba Sticks")
            }
            LocationId::Deku_Tree__Lobby__Center__Deku_Baby_Nuts => {
                write!(f, "{}", "Deku Tree > Lobby > Center Deku Baby Nuts")
            }
            LocationId::Deku_Tree__Lobby__Center__Web => {
                write!(f, "{}", "Deku Tree > Lobby > Center Web")
            }
            LocationId::Deku_Tree__Floor_2__Vines__Map_Chest => {
                write!(f, "{}", "Deku Tree > Floor 2 > Vines Map Chest")
            }
            LocationId::Deku_Tree__Scrub_Room__Entry__Scrub => {
                write!(f, "{}", "Deku Tree > Scrub Room > Entry Scrub")
            }
            LocationId::Deku_Tree__Slingshot_Room__Slingshot__Chest => {
                write!(f, "{}", "Deku Tree > Slingshot Room > Slingshot Chest")
            }
            LocationId::Deku_Tree__Slingshot_Upper__Ledge__Chest => {
                write!(f, "{}", "Deku Tree > Slingshot Upper > Ledge Chest")
            }
            LocationId::Deku_Tree__Floor_3__Door__Break_Web => {
                write!(f, "{}", "Deku Tree > Floor 3 > Door Break Web")
            }
            LocationId::Deku_Tree__Compass_Room__Entry__Burn_Web => {
                write!(f, "{}", "Deku Tree > Compass Room > Entry Burn Web")
            }
            LocationId::Deku_Tree__Compass_Room__Compass__Chest => {
                write!(f, "{}", "Deku Tree > Compass Room > Compass Chest")
            }
            LocationId::Deku_Tree__Compass_Room__Ledge__Chest => {
                write!(f, "{}", "Deku Tree > Compass Room > Ledge Chest")
            }
            LocationId::Deku_Tree__Compass_Room__Ledge__GS => {
                write!(f, "{}", "Deku Tree > Compass Room > Ledge GS")
            }
            LocationId::Deku_Tree__Basement_1__Center__Vines_GS => {
                write!(f, "{}", "Deku Tree > Basement 1 > Center Vines GS")
            }
            LocationId::Deku_Tree__Basement_1__Corner__Switch => {
                write!(f, "{}", "Deku Tree > Basement 1 > Corner Switch")
            }
            LocationId::Deku_Tree__Basement_1__Corner__Chest => {
                write!(f, "{}", "Deku Tree > Basement 1 > Corner Chest")
            }
            LocationId::Deku_Tree__Basement_1__Corner__Gate_GS => {
                write!(f, "{}", "Deku Tree > Basement 1 > Corner Gate GS")
            }
            LocationId::Deku_Tree__Basement_1__Corner__Burn_Basement_Web => {
                write!(f, "{}", "Deku Tree > Basement 1 > Corner Burn Basement Web")
            }
            LocationId::Deku_Tree__Back_Room__Northwest__Burn_Web => {
                write!(f, "{}", "Deku Tree > Back Room > Northwest Burn Web")
            }
            LocationId::Deku_Tree__Back_Room__Northwest__Break_Wall => {
                write!(f, "{}", "Deku Tree > Back Room > Northwest Break Wall")
            }
            LocationId::Deku_Tree__Skull_Room__Entry__GS => {
                write!(f, "{}", "Deku Tree > Skull Room > Entry GS")
            }
            LocationId::Deku_Tree__Basement_Ledge__Block__Push_Block => {
                write!(f, "{}", "Deku Tree > Basement Ledge > Block Push Block")
            }
            LocationId::Deku_Tree__Basement_Ledge__Web__Burn_Web => {
                write!(f, "{}", "Deku Tree > Basement Ledge > Web Burn Web")
            }
            LocationId::Deku_Tree__Basement_2__Boss_Door__Scrubs => {
                write!(f, "{}", "Deku Tree > Basement 2 > Boss Door Scrubs")
            }
            LocationId::Deku_Tree__Boss_Room__Arena__Gohma => {
                write!(f, "{}", "Deku Tree > Boss Room > Arena Gohma")
            }
            LocationId::Deku_Tree__Boss_Room__Arena__Gohma_Quick_Kill => {
                write!(f, "{}", "Deku Tree > Boss Room > Arena Gohma Quick Kill")
            }
            LocationId::Deku_Tree__Boss_Room__Arena__Gohma_Heart => {
                write!(f, "{}", "Deku Tree > Boss Room > Arena Gohma Heart")
            }
            LocationId::Deku_Tree__Boss_Room__Arena__Blue_Warp => {
                write!(f, "{}", "Deku Tree > Boss Room > Arena Blue Warp")
            }
            LocationId::KF__Kokiri_Village__Midos_Guardpost__Show_Mido => {
                write!(f, "{}", "KF > Kokiri Village > Mido's Guardpost Show Mido")
            }
            LocationId::KF__Boulder_Maze__Reward__Chest => {
                write!(f, "{}", "KF > Boulder Maze > Reward Chest")
            }
            LocationId::KF__Baba_Corridor__Deku_Babas__Sticks => {
                write!(f, "{}", "KF > Baba Corridor > Deku Babas Sticks")
            }
            LocationId::KF__Baba_Corridor__Deku_Babas__Nuts => {
                write!(f, "{}", "KF > Baba Corridor > Deku Babas Nuts")
            }
            LocationId::KF__Outside_Deku_Tree__Left__Gossip_Stone => {
                write!(f, "{}", "KF > Outside Deku Tree > Left Gossip Stone")
            }
            LocationId::KF__Outside_Deku_Tree__Right__Gossip_Stone => {
                write!(f, "{}", "KF > Outside Deku Tree > Right Gossip Stone")
            }
            LocationId::KF__Midos_House__Entry__Top_Left_Chest => {
                write!(f, "{}", "KF > Mido's House > Entry Top Left Chest")
            }
            LocationId::KF__Midos_House__Entry__Top_Right_Chest => {
                write!(f, "{}", "KF > Mido's House > Entry Top Right Chest")
            }
            LocationId::KF__Midos_House__Entry__Bottom_Left_Chest => {
                write!(f, "{}", "KF > Mido's House > Entry Bottom Left Chest")
            }
            LocationId::KF__Midos_House__Entry__Bottom_Right_Chest => {
                write!(f, "{}", "KF > Mido's House > Entry Bottom Right Chest")
            }
            LocationId::KF__Shop__Entry__Blue_Rupee => {
                write!(f, "{}", "KF > Shop > Entry Blue Rupee")
            }
            LocationId::KF__Shop__Entry__Item_1 => write!(f, "{}", "KF > Shop > Entry Item 1"),
            LocationId::KF__Shop__Entry__Item_2 => write!(f, "{}", "KF > Shop > Entry Item 2"),
            LocationId::KF__Shop__Entry__Item_3 => write!(f, "{}", "KF > Shop > Entry Item 3"),
            LocationId::KF__Shop__Entry__Item_4 => write!(f, "{}", "KF > Shop > Entry Item 4"),
            LocationId::KF__Shop__Entry__Item_5 => write!(f, "{}", "KF > Shop > Entry Item 5"),
            LocationId::KF__Shop__Entry__Item_6 => write!(f, "{}", "KF > Shop > Entry Item 6"),
            LocationId::KF__Shop__Entry__Item_7 => write!(f, "{}", "KF > Shop > Entry Item 7"),
            LocationId::KF__Shop__Entry__Item_8 => write!(f, "{}", "KF > Shop > Entry Item 8"),
            LocationId::Kak__Spider_House__Entry__Skulls_10 => {
                write!(f, "{}", "Kak > Spider House > Entry Skulls 10")
            }
        }
    }
}

#[derive(Debug, PartialEq, Eq, Copy, Clone, enum_map::Enum)]
pub enum ExitId {
    Deku_Tree__Lobby__Center__ex__Basement_1__Center_1,
    Deku_Tree__Lobby__Center__ex__Basement_Ledge__Block_1,
    Deku_Tree__Lobby__Vines__ex__Floor_2__Lower_1,
    Deku_Tree__Floor_2__Lower__ex__Lobby__Vines_1,
    Deku_Tree__Floor_2__Vines__ex__Floor_3__Climb_1,
    Deku_Tree__Floor_2__Vines__ex__Floor_3__Climb_2,
    Deku_Tree__Floor_2__Vines__ex__Lobby__Vines_1,
    Deku_Tree__Floor_2__Vines__ex__Lobby__Entry_1,
    Deku_Tree__Floor_2__Slingshot_Door__ex__Scrub_Room__Entry_1,
    Deku_Tree__Floor_2__Slingshot_Door__ex__Lobby__Entry_1,
    Deku_Tree__Scrub_Room__Rear__ex__Slingshot_Room__Entry_1,
    Deku_Tree__Slingshot_Room__Entry__ex__Scrub_Room__Rear_1,
    Deku_Tree__Slingshot_Room__Slingshot__ex__Slingshot_Upper__Ledge_1,
    Deku_Tree__Slingshot_Upper__Ledge__ex__Slingshot_Room__Slingshot_1,
    Deku_Tree__Floor_3__Door__ex__Compass_Room__Entry_1,
    Deku_Tree__Floor_3__Door__ex__Lobby__Center_1,
    Deku_Tree__Floor_3__Door__Break_Web,
    Deku_Tree__Compass_Room__Entry__ex__Floor_3__Door_1,
    Deku_Tree__Compass_Room__Entry__Burn_Web,
    Deku_Tree__Compass_Room__Compass__ex__Ledge_1,
    Deku_Tree__Compass_Room__Ledge__ex__Compass_1,
    Deku_Tree__Basement_1__Center__ex__Lobby__Center_1,
    Deku_Tree__Basement_1__Corner__ex__Basement_Ledge__Block_1,
    Deku_Tree__Basement_1__Corner__Burn_Basement_Web,
    Deku_Tree__Basement_1__South_Door__ex__Back_Room__South_1,
    Deku_Tree__Back_Room__Northwest__ex__Skull_Room__Entry_1,
    Deku_Tree__Back_Room__East__ex__Basement_Ledge__Web_1,
    Deku_Tree__Skull_Room__Entry__ex__Back_Room__Northweest_1,
    Deku_Tree__Basement_Ledge__Block__ex__Basement_1__Corner_1,
    Deku_Tree__Basement_Ledge__Web__ex__Basement_2__Pool_1,
    Deku_Tree__Basement_2__Pool__ex__Basement_Ledge__Web_1,
    Deku_Tree__Basement_2__Boss_Door__ex__Boss_Room__Entry_1,
    Deku_Tree__Boss_Room__Arena__Blue_Warp,
    KF__Links_House__Entry__ex__Kokiri_Village__Links_Porch_1,
    KF__Kokiri_Village__Links_Porch__ex__Links_House__Entry_1,
    KF__Kokiri_Village__Links_Porch__ex__Knowitall_Porch_1,
    KF__Kokiri_Village__Links_Porch__ex__Training_Center_1,
    KF__Kokiri_Village__Links_Porch__ex__Midos_Guardpost_1,
    KF__Kokiri_Village__Midos_Porch__ex__Midos_House__Entry_1,
    KF__Kokiri_Village__Knowitall_Porch__ex__Knowitall_House__Entry_1,
    KF__Kokiri_Village__Training_Center__ex__Boulder_Maze__Entry_1,
    KF__Kokiri_Village__Shop_Porch__ex__Shop__Entry_1,
    KF__Kokiri_Village__Sarias_Porch__ex__Kak__Spider_House__Entry_1,
    KF__Kokiri_Village__Midos_Guardpost__ex__Baba_Corridor__Village_Side_1,
    KF__Boulder_Maze__Entry__ex__Kokiri_Village__Training_Center_1,
    KF__Baba_Corridor__Village_Side__ex__Kokiri_Village__Midos_Guardpost_1,
    KF__Baba_Corridor__Tree_Side__ex__Outside_Deku_Tree__Entry_1,
    KF__Outside_Deku_Tree__Entry__ex__Baba_Corridor__Tree_Side_1,
    KF__Outside_Deku_Tree__Mouth__ex__Deku_Tree__Lobby__Entry_1,
    KF__Midos_House__Entry__ex__Kokiri_Village__Midos_Porch_1,
    KF__Knowitall_House__Entry__ex__Kokiri_Village__Knowitall_Porch_1,
    KF__Shop__Entry__ex__Kokiri_Village__Shop_Porch_1,
    Kak__Spider_House__Entry__ex__KF__Kokiri_Village__Sarias_Porch_1,
}
impl fmt::Display for ExitId {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            ExitId::Deku_Tree__Lobby__Center__ex__Basement_1__Center_1 => write!(
                f,
                "{}",
                "Deku Tree > Lobby > Center ==> Basement 1 > Center (1)"
            ),
            ExitId::Deku_Tree__Lobby__Center__ex__Basement_Ledge__Block_1 => write!(
                f,
                "{}",
                "Deku Tree > Lobby > Center ==> Basement Ledge > Block (1)"
            ),
            ExitId::Deku_Tree__Lobby__Vines__ex__Floor_2__Lower_1 => {
                write!(f, "{}", "Deku Tree > Lobby > Vines ==> Floor 2 > Lower (1)")
            }
            ExitId::Deku_Tree__Floor_2__Lower__ex__Lobby__Vines_1 => {
                write!(f, "{}", "Deku Tree > Floor 2 > Lower ==> Lobby > Vines (1)")
            }
            ExitId::Deku_Tree__Floor_2__Vines__ex__Floor_3__Climb_1 => write!(
                f,
                "{}",
                "Deku Tree > Floor 2 > Vines ==> Floor 3 > Climb (1)"
            ),
            ExitId::Deku_Tree__Floor_2__Vines__ex__Floor_3__Climb_2 => write!(
                f,
                "{}",
                "Deku Tree > Floor 2 > Vines ==> Floor 3 > Climb (2)"
            ),
            ExitId::Deku_Tree__Floor_2__Vines__ex__Lobby__Vines_1 => {
                write!(f, "{}", "Deku Tree > Floor 2 > Vines ==> Lobby > Vines (1)")
            }
            ExitId::Deku_Tree__Floor_2__Vines__ex__Lobby__Entry_1 => {
                write!(f, "{}", "Deku Tree > Floor 2 > Vines ==> Lobby > Entry (1)")
            }
            ExitId::Deku_Tree__Floor_2__Slingshot_Door__ex__Scrub_Room__Entry_1 => write!(
                f,
                "{}",
                "Deku Tree > Floor 2 > Slingshot Door ==> Scrub Room > Entry (1)"
            ),
            ExitId::Deku_Tree__Floor_2__Slingshot_Door__ex__Lobby__Entry_1 => write!(
                f,
                "{}",
                "Deku Tree > Floor 2 > Slingshot Door ==> Lobby > Entry (1)"
            ),
            ExitId::Deku_Tree__Scrub_Room__Rear__ex__Slingshot_Room__Entry_1 => write!(
                f,
                "{}",
                "Deku Tree > Scrub Room > Rear ==> Slingshot Room > Entry (1)"
            ),
            ExitId::Deku_Tree__Slingshot_Room__Entry__ex__Scrub_Room__Rear_1 => write!(
                f,
                "{}",
                "Deku Tree > Slingshot Room > Entry ==> Scrub Room > Rear (1)"
            ),
            ExitId::Deku_Tree__Slingshot_Room__Slingshot__ex__Slingshot_Upper__Ledge_1 => write!(
                f,
                "{}",
                "Deku Tree > Slingshot Room > Slingshot ==> Slingshot Upper > Ledge (1)"
            ),
            ExitId::Deku_Tree__Slingshot_Upper__Ledge__ex__Slingshot_Room__Slingshot_1 => write!(
                f,
                "{}",
                "Deku Tree > Slingshot Upper > Ledge ==> Slingshot Room > Slingshot (1)"
            ),
            ExitId::Deku_Tree__Floor_3__Door__ex__Compass_Room__Entry_1 => write!(
                f,
                "{}",
                "Deku Tree > Floor 3 > Door ==> Compass Room > Entry (1)"
            ),
            ExitId::Deku_Tree__Floor_3__Door__ex__Lobby__Center_1 => {
                write!(f, "{}", "Deku Tree > Floor 3 > Door ==> Lobby > Center (1)")
            }
            ExitId::Deku_Tree__Floor_3__Door__Break_Web => {
                write!(f, "{}", "Deku Tree > Floor 3 > Door Break Web")
            }
            ExitId::Deku_Tree__Compass_Room__Entry__ex__Floor_3__Door_1 => write!(
                f,
                "{}",
                "Deku Tree > Compass Room > Entry ==> Floor 3 > Door (1)"
            ),
            ExitId::Deku_Tree__Compass_Room__Entry__Burn_Web => {
                write!(f, "{}", "Deku Tree > Compass Room > Entry Burn Web")
            }
            ExitId::Deku_Tree__Compass_Room__Compass__ex__Ledge_1 => {
                write!(f, "{}", "Deku Tree > Compass Room > Compass ==> Ledge (1)")
            }
            ExitId::Deku_Tree__Compass_Room__Ledge__ex__Compass_1 => {
                write!(f, "{}", "Deku Tree > Compass Room > Ledge ==> Compass (1)")
            }
            ExitId::Deku_Tree__Basement_1__Center__ex__Lobby__Center_1 => write!(
                f,
                "{}",
                "Deku Tree > Basement 1 > Center ==> Lobby > Center (1)"
            ),
            ExitId::Deku_Tree__Basement_1__Corner__ex__Basement_Ledge__Block_1 => write!(
                f,
                "{}",
                "Deku Tree > Basement 1 > Corner ==> Basement Ledge > Block (1)"
            ),
            ExitId::Deku_Tree__Basement_1__Corner__Burn_Basement_Web => {
                write!(f, "{}", "Deku Tree > Basement 1 > Corner Burn Basement Web")
            }
            ExitId::Deku_Tree__Basement_1__South_Door__ex__Back_Room__South_1 => write!(
                f,
                "{}",
                "Deku Tree > Basement 1 > South Door ==> Back Room > South (1)"
            ),
            ExitId::Deku_Tree__Back_Room__Northwest__ex__Skull_Room__Entry_1 => write!(
                f,
                "{}",
                "Deku Tree > Back Room > Northwest ==> Skull Room > Entry (1)"
            ),
            ExitId::Deku_Tree__Back_Room__East__ex__Basement_Ledge__Web_1 => write!(
                f,
                "{}",
                "Deku Tree > Back Room > East ==> Basement Ledge > Web (1)"
            ),
            ExitId::Deku_Tree__Skull_Room__Entry__ex__Back_Room__Northweest_1 => write!(
                f,
                "{}",
                "Deku Tree > Skull Room > Entry ==> Back Room > Northweest (1)"
            ),
            ExitId::Deku_Tree__Basement_Ledge__Block__ex__Basement_1__Corner_1 => write!(
                f,
                "{}",
                "Deku Tree > Basement Ledge > Block ==> Basement 1 > Corner (1)"
            ),
            ExitId::Deku_Tree__Basement_Ledge__Web__ex__Basement_2__Pool_1 => write!(
                f,
                "{}",
                "Deku Tree > Basement Ledge > Web ==> Basement 2 > Pool (1)"
            ),
            ExitId::Deku_Tree__Basement_2__Pool__ex__Basement_Ledge__Web_1 => write!(
                f,
                "{}",
                "Deku Tree > Basement 2 > Pool ==> Basement Ledge > Web (1)"
            ),
            ExitId::Deku_Tree__Basement_2__Boss_Door__ex__Boss_Room__Entry_1 => write!(
                f,
                "{}",
                "Deku Tree > Basement 2 > Boss Door ==> Boss Room > Entry (1)"
            ),
            ExitId::Deku_Tree__Boss_Room__Arena__Blue_Warp => {
                write!(f, "{}", "Deku Tree > Boss Room > Arena Blue Warp")
            }
            ExitId::KF__Links_House__Entry__ex__Kokiri_Village__Links_Porch_1 => write!(
                f,
                "{}",
                "KF > Link's House > Entry ==> Kokiri Village > Link's Porch (1)"
            ),
            ExitId::KF__Kokiri_Village__Links_Porch__ex__Links_House__Entry_1 => write!(
                f,
                "{}",
                "KF > Kokiri Village > Link's Porch ==> Link's House > Entry (1)"
            ),
            ExitId::KF__Kokiri_Village__Links_Porch__ex__Knowitall_Porch_1 => write!(
                f,
                "{}",
                "KF > Kokiri Village > Link's Porch ==> Know-it-all Porch (1)"
            ),
            ExitId::KF__Kokiri_Village__Links_Porch__ex__Training_Center_1 => write!(
                f,
                "{}",
                "KF > Kokiri Village > Link's Porch ==> Training Center (1)"
            ),
            ExitId::KF__Kokiri_Village__Links_Porch__ex__Midos_Guardpost_1 => write!(
                f,
                "{}",
                "KF > Kokiri Village > Link's Porch ==> Mido's Guardpost (1)"
            ),
            ExitId::KF__Kokiri_Village__Midos_Porch__ex__Midos_House__Entry_1 => write!(
                f,
                "{}",
                "KF > Kokiri Village > Mido's Porch ==> Mido's House > Entry (1)"
            ),
            ExitId::KF__Kokiri_Village__Knowitall_Porch__ex__Knowitall_House__Entry_1 => write!(
                f,
                "{}",
                "KF > Kokiri Village > Know-it-all Porch ==> Know-it-all House > Entry (1)"
            ),
            ExitId::KF__Kokiri_Village__Training_Center__ex__Boulder_Maze__Entry_1 => write!(
                f,
                "{}",
                "KF > Kokiri Village > Training Center ==> Boulder Maze > Entry (1)"
            ),
            ExitId::KF__Kokiri_Village__Shop_Porch__ex__Shop__Entry_1 => write!(
                f,
                "{}",
                "KF > Kokiri Village > Shop Porch ==> Shop > Entry (1)"
            ),
            ExitId::KF__Kokiri_Village__Sarias_Porch__ex__Kak__Spider_House__Entry_1 => write!(
                f,
                "{}",
                "KF > Kokiri Village > Saria's Porch ==> Kak > Spider House > Entry (1)"
            ),
            ExitId::KF__Kokiri_Village__Midos_Guardpost__ex__Baba_Corridor__Village_Side_1 => {
                write!(
                    f,
                    "{}",
                    "KF > Kokiri Village > Mido's Guardpost ==> Baba Corridor > Village Side (1)"
                )
            }
            ExitId::KF__Boulder_Maze__Entry__ex__Kokiri_Village__Training_Center_1 => write!(
                f,
                "{}",
                "KF > Boulder Maze > Entry ==> Kokiri Village > Training Center (1)"
            ),
            ExitId::KF__Baba_Corridor__Village_Side__ex__Kokiri_Village__Midos_Guardpost_1 => {
                write!(
                    f,
                    "{}",
                    "KF > Baba Corridor > Village Side ==> Kokiri Village > Mido's Guardpost (1)"
                )
            }
            ExitId::KF__Baba_Corridor__Tree_Side__ex__Outside_Deku_Tree__Entry_1 => write!(
                f,
                "{}",
                "KF > Baba Corridor > Tree Side ==> Outside Deku Tree > Entry (1)"
            ),
            ExitId::KF__Outside_Deku_Tree__Entry__ex__Baba_Corridor__Tree_Side_1 => write!(
                f,
                "{}",
                "KF > Outside Deku Tree > Entry ==> Baba Corridor > Tree Side (1)"
            ),
            ExitId::KF__Outside_Deku_Tree__Mouth__ex__Deku_Tree__Lobby__Entry_1 => write!(
                f,
                "{}",
                "KF > Outside Deku Tree > Mouth ==> Deku Tree > Lobby > Entry (1)"
            ),
            ExitId::KF__Midos_House__Entry__ex__Kokiri_Village__Midos_Porch_1 => write!(
                f,
                "{}",
                "KF > Mido's House > Entry ==> Kokiri Village > Mido's Porch (1)"
            ),
            ExitId::KF__Knowitall_House__Entry__ex__Kokiri_Village__Knowitall_Porch_1 => write!(
                f,
                "{}",
                "KF > Know-it-all House > Entry ==> Kokiri Village > Know-it-all Porch (1)"
            ),
            ExitId::KF__Shop__Entry__ex__Kokiri_Village__Shop_Porch_1 => write!(
                f,
                "{}",
                "KF > Shop > Entry ==> Kokiri Village > Shop Porch (1)"
            ),
            ExitId::Kak__Spider_House__Entry__ex__KF__Kokiri_Village__Sarias_Porch_1 => write!(
                f,
                "{}",
                "Kak > Spider House > Entry ==> KF > Kokiri Village > Saria's Porch (1)"
            ),
        }
    }
}

#[derive(Debug, PartialEq, Eq, Copy, Clone, enum_map::Enum)]
pub enum ActionId {
    Deku_Tree__Compass_Room__Entry__Light_Torch,
}
impl fmt::Display for ActionId {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            ActionId::Deku_Tree__Compass_Room__Entry__Light_Torch => {
                write!(f, "{}", "Deku Tree > Compass Room > Entry Light Torch")
            }
        }
    }
}

#[derive(Debug, PartialEq, Eq, Copy, Clone, enum_map::Enum, Default)]
pub enum CanonId {
    #[default]
    None,
    Deku_Lobby_Web,
    Deku_Basement_Web,
    Defeat_Gohma,
}
impl fmt::Display for CanonId {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            CanonId::None => write!(f, "{}", "None"),
            CanonId::Deku_Lobby_Web => write!(f, "{}", "Deku_Lobby_Web"),
            CanonId::Deku_Basement_Web => write!(f, "{}", "Deku_Basement_Web"),
            CanonId::Defeat_Gohma => write!(f, "{}", "Defeat_Gohma"),
        }
    }
}

#[derive(Debug, PartialEq, Eq, Copy, Clone)]
pub enum History {
    Warp(SpotId),
    Get(LocationId),
    Move(ExitId),
    Activate(ActionId),
}

#[derive(Copy, Clone)]
pub struct Location {
    id: LocationId,
    item: Item,
    canonical: CanonId,
    time: i8,
    pub price: Currency,

    pub access_rule: fn(&Context) -> bool,
}

impl world::Accessible for Location {
    type Context = Context;
    fn can_access(&self, ctx: &Context) -> bool {
        ctx.can_afford(&self.price) && (self.access_rule)(ctx)
    }
}

impl world::Location for Location {
    type LocId = LocationId;
    type CanonId = CanonId;

    fn id(&self) -> &LocationId {
        &self.id
    }
    fn item(&self) -> &Item {
        &self.item
    }

    fn canon_id(&self) -> &CanonId {
        &self.canonical
    }
}

impl Location {
    pub fn access(&self, ctx: &Context) -> bool {
        ctx.can_afford(&self.price)
            && match self.id {
                LocationId::Deku_Tree__Lobby__Center__Deku_Baba_Sticks => {
                    ctx.has(&Item::Hover_Boots)
                }
                LocationId::Deku_Tree__Lobby__Center__Deku_Baby_Nuts => ctx.has(&Item::Slingshot),
                LocationId::Deku_Tree__Lobby__Center__Web => ctx.has(&Item::Hylian_Shield),
                LocationId::Deku_Tree__Floor_2__Vines__Map_Chest => ctx.has(&Item::Boomerang),
                LocationId::Deku_Tree__Scrub_Room__Entry__Scrub => ctx.has(&Item::Nayrus_Love),
                LocationId::Deku_Tree__Slingshot_Room__Slingshot__Chest => {
                    ctx.has(&Item::Compass_Deku_Tree)
                }
                LocationId::Deku_Tree__Slingshot_Upper__Ledge__Chest => {
                    ctx.has(&Item::Heart_Container)
                }
                LocationId::Deku_Tree__Floor_3__Door__Break_Web => ctx.has(&Item::Dins_Fire),
                LocationId::Deku_Tree__Compass_Room__Entry__Burn_Web => ctx.has(&Item::Rupees_50),
                LocationId::Deku_Tree__Compass_Room__Compass__Chest => {
                    ctx.has(&Item::Deku_Nut_Drop)
                }
                LocationId::Deku_Tree__Compass_Room__Ledge__Chest => ctx.has(&Item::Farores_Wind),
                LocationId::Deku_Tree__Compass_Room__Ledge__GS => ctx.has(&Item::Buy_Deku_Seeds_30),
                LocationId::Deku_Tree__Basement_1__Center__Vines_GS => {
                    ctx.has(&Item::Buy_Deku_Shield)
                }
                LocationId::Deku_Tree__Basement_1__Corner__Switch => {
                    ctx.has(&Item::Gold_Skulltula_Token)
                }
                LocationId::Deku_Tree__Basement_1__Corner__Chest => {
                    ctx.has(&Item::Deku_Back_Room_Web)
                }
                LocationId::Deku_Tree__Basement_1__Corner__Gate_GS => ctx.has(&Item::Hover_Boots),
                LocationId::Deku_Tree__Basement_1__Corner__Burn_Basement_Web => {
                    ctx.has(&Item::Dins_Fire)
                }
                LocationId::Deku_Tree__Back_Room__Northwest__Burn_Web => {
                    ctx.has(&Item::Buy_Deku_Stick_1)
                }
                LocationId::Deku_Tree__Back_Room__Northwest__Break_Wall => {
                    ctx.has(&Item::Magic_Meter)
                }
                LocationId::Deku_Tree__Skull_Room__Entry__GS => ctx.has(&Item::Heart_Container),
                LocationId::Deku_Tree__Basement_Ledge__Block__Push_Block => {
                    ctx.has(&Item::Rupees_50)
                }
                LocationId::Deku_Tree__Basement_Ledge__Web__Burn_Web => {
                    ctx.has(&Item::Buy_Arrows_10)
                }
                LocationId::Deku_Tree__Basement_2__Boss_Door__Scrubs => ctx.has(&Item::Rupees_5),
                LocationId::Deku_Tree__Boss_Room__Arena__Gohma => ctx.has(&Item::Farores_Wind),
                LocationId::Deku_Tree__Boss_Room__Arena__Gohma_Quick_Kill => {
                    ctx.has(&Item::Deku_Shield_Drop)
                }
                LocationId::Deku_Tree__Boss_Room__Arena__Gohma_Heart => ctx.has(&Item::Boomerang),
                LocationId::Deku_Tree__Boss_Room__Arena__Blue_Warp => {
                    ctx.has(&Item::Deku_Back_Room_Wall)
                }
                LocationId::KF__Kokiri_Village__Midos_Guardpost__Show_Mido => {
                    ctx.has(&Item::Deku_Basement_Web)
                }
                LocationId::KF__Boulder_Maze__Reward__Chest => ctx.has(&Item::Rupees_50),
                LocationId::KF__Baba_Corridor__Deku_Babas__Sticks => ctx.has(&Item::Arrows_10),
                LocationId::KF__Baba_Corridor__Deku_Babas__Nuts => ctx.has(&Item::Deku_Shield_Drop),
                LocationId::KF__Outside_Deku_Tree__Left__Gossip_Stone => {
                    ctx.has(&Item::Buy_Arrows_30)
                }
                LocationId::KF__Outside_Deku_Tree__Right__Gossip_Stone => ctx.has(&Item::Rupee_1),
                LocationId::KF__Midos_House__Entry__Top_Left_Chest => ctx.has(&Item::Bow),
                LocationId::KF__Midos_House__Entry__Top_Right_Chest => ctx.has(&Item::Nayrus_Love),
                LocationId::KF__Midos_House__Entry__Bottom_Left_Chest => ctx.has(&Item::Ocarina),
                LocationId::KF__Midos_House__Entry__Bottom_Right_Chest => {
                    ctx.has(&Item::Nayrus_Love)
                }
                LocationId::KF__Shop__Entry__Blue_Rupee => ctx.has(&Item::Defeat_Ganon),
                LocationId::KF__Shop__Entry__Item_1 => ctx.has(&Item::Blue_Fire_Arrows),
                LocationId::KF__Shop__Entry__Item_2 => ctx.has(&Item::Map_Deku_Tree),
                LocationId::KF__Shop__Entry__Item_3 => ctx.has(&Item::Buy_Heart),
                LocationId::KF__Shop__Entry__Item_4 => ctx.has(&Item::Blue_Fire_Arrows),
                LocationId::KF__Shop__Entry__Item_5 => ctx.has(&Item::Buy_Arrows_10),
                LocationId::KF__Shop__Entry__Item_6 => ctx.has(&Item::Showed_Mido),
                LocationId::KF__Shop__Entry__Item_7 => ctx.has(&Item::Deku_Lobby_Web),
                LocationId::KF__Shop__Entry__Item_8 => ctx.has(&Item::Zora_Tunic),
                LocationId::Kak__Spider_House__Entry__Skulls_10 => ctx.has(&Item::Megaton_Hammer),
            }
    }
}

pub fn locaccess_Deku_Tree__Lobby__Center__Deku_Baba_Sticks(ctx: &Context) -> bool {
    ctx.has(&Item::Showed_Mido)
}
pub fn locaccess_Deku_Tree__Lobby__Center__Deku_Baby_Nuts(ctx: &Context) -> bool {
    ctx.has(&Item::Boomerang)
}
pub fn locaccess_Deku_Tree__Lobby__Center__Web(ctx: &Context) -> bool {
    ctx.has(&Item::Rupee_1)
}
pub fn locaccess_Deku_Tree__Floor_2__Vines__Map_Chest(ctx: &Context) -> bool {
    ctx.has(&Item::Buy_Deku_Stick_1)
}
pub fn locaccess_Deku_Tree__Scrub_Room__Entry__Scrub(ctx: &Context) -> bool {
    ctx.has(&Item::Arrows_10)
}
pub fn locaccess_Deku_Tree__Slingshot_Room__Slingshot__Chest(ctx: &Context) -> bool {
    ctx.has(&Item::Defeat_Ganon)
}
pub fn locaccess_Deku_Tree__Slingshot_Upper__Ledge__Chest(ctx: &Context) -> bool {
    ctx.has(&Item::Deku_Stick_Drop)
}
pub fn locaccess_Deku_Tree__Floor_3__Door__Break_Web(ctx: &Context) -> bool {
    ctx.has(&Item::Nayrus_Love)
}
pub fn locaccess_Deku_Tree__Compass_Room__Entry__Burn_Web(ctx: &Context) -> bool {
    ctx.has(&Item::Deku_Lobby_Web)
}
pub fn locaccess_Deku_Tree__Compass_Room__Compass__Chest(ctx: &Context) -> bool {
    ctx.has(&Item::Mirror_Shield)
}
pub fn locaccess_Deku_Tree__Compass_Room__Ledge__Chest(ctx: &Context) -> bool {
    ctx.has(&Item::Deku_Nut_Drop)
}
pub fn locaccess_Deku_Tree__Compass_Room__Ledge__GS(ctx: &Context) -> bool {
    ctx.has(&Item::Rupees_5)
}
pub fn locaccess_Deku_Tree__Basement_1__Center__Vines_GS(ctx: &Context) -> bool {
    ctx.has(&Item::Hover_Boots)
}
pub fn locaccess_Deku_Tree__Basement_1__Corner__Switch(ctx: &Context) -> bool {
    ctx.has(&Item::Hylian_Shield)
}
pub fn locaccess_Deku_Tree__Basement_1__Corner__Chest(ctx: &Context) -> bool {
    ctx.has(&Item::Goron_Tunic)
}
pub fn locaccess_Deku_Tree__Basement_1__Corner__Gate_GS(ctx: &Context) -> bool {
    ctx.has(&Item::Compass_Deku_Tree)
}
pub fn locaccess_Deku_Tree__Basement_1__Corner__Burn_Basement_Web(ctx: &Context) -> bool {
    ctx.has(&Item::Buy_Deku_Seeds_30)
}
pub fn locaccess_Deku_Tree__Back_Room__Northwest__Burn_Web(ctx: &Context) -> bool {
    ctx.has(&Item::Rupee_1)
}
pub fn locaccess_Deku_Tree__Back_Room__Northwest__Break_Wall(ctx: &Context) -> bool {
    ctx.has(&Item::Arrows_10)
}
pub fn locaccess_Deku_Tree__Skull_Room__Entry__GS(ctx: &Context) -> bool {
    ctx.has(&Item::Gold_Skulltula_Token)
}
pub fn locaccess_Deku_Tree__Basement_Ledge__Block__Push_Block(ctx: &Context) -> bool {
    ctx.has(&Item::Minuet_of_Forest)
}
pub fn locaccess_Deku_Tree__Basement_Ledge__Web__Burn_Web(ctx: &Context) -> bool {
    ctx.has(&Item::Deku_Lobby_Web)
}
pub fn locaccess_Deku_Tree__Basement_2__Boss_Door__Scrubs(ctx: &Context) -> bool {
    ctx.has(&Item::Deku_Basement_Switch)
}
pub fn locaccess_Deku_Tree__Boss_Room__Arena__Gohma(ctx: &Context) -> bool {
    ctx.has(&Item::Hover_Boots)
}
pub fn locaccess_Deku_Tree__Boss_Room__Arena__Gohma_Quick_Kill(ctx: &Context) -> bool {
    ctx.has(&Item::Zora_Tunic)
}
pub fn locaccess_Deku_Tree__Boss_Room__Arena__Gohma_Heart(ctx: &Context) -> bool {
    ctx.has(&Item::Kokiri_Sword)
}
pub fn locaccess_Deku_Tree__Boss_Room__Arena__Blue_Warp(ctx: &Context) -> bool {
    ctx.has(&Item::Magic_Meter)
}
pub fn locaccess_KF__Kokiri_Village__Midos_Guardpost__Show_Mido(ctx: &Context) -> bool {
    ctx.has(&Item::Iron_Boots)
}
pub fn locaccess_KF__Boulder_Maze__Reward__Chest(ctx: &Context) -> bool {
    ctx.has(&Item::Arrows_10)
}
pub fn locaccess_KF__Baba_Corridor__Deku_Babas__Sticks(ctx: &Context) -> bool {
    ctx.has(&Item::Defeat_Ganon)
}
pub fn locaccess_KF__Baba_Corridor__Deku_Babas__Nuts(ctx: &Context) -> bool {
    ctx.has(&Item::Buy_Arrows_10)
}
pub fn locaccess_KF__Outside_Deku_Tree__Left__Gossip_Stone(ctx: &Context) -> bool {
    ctx.has(&Item::Heart_Container)
}
pub fn locaccess_KF__Outside_Deku_Tree__Right__Gossip_Stone(ctx: &Context) -> bool {
    ctx.has(&Item::Deku_Stick_Drop)
}
pub fn locaccess_KF__Midos_House__Entry__Top_Left_Chest(ctx: &Context) -> bool {
    ctx.has(&Item::Gold_Skulltula_Token)
}
pub fn locaccess_KF__Midos_House__Entry__Top_Right_Chest(ctx: &Context) -> bool {
    ctx.has(&Item::Dins_Fire)
}
pub fn locaccess_KF__Midos_House__Entry__Bottom_Left_Chest(ctx: &Context) -> bool {
    ctx.has(&Item::Deku_Stick_Drop)
}
pub fn locaccess_KF__Midos_House__Entry__Bottom_Right_Chest(ctx: &Context) -> bool {
    ctx.has(&Item::Bow)
}
pub fn locaccess_KF__Shop__Entry__Blue_Rupee(ctx: &Context) -> bool {
    ctx.has(&Item::Biggoron_Sword)
}
pub fn locaccess_KF__Shop__Entry__Item_1(ctx: &Context) -> bool {
    ctx.has(&Item::Lens_of_Truth)
}
pub fn locaccess_KF__Shop__Entry__Item_2(ctx: &Context) -> bool {
    ctx.has(&Item::Kokiri_Sword)
}
pub fn locaccess_KF__Shop__Entry__Item_3(ctx: &Context) -> bool {
    ctx.has(&Item::Kokiri_Emerald)
}
pub fn locaccess_KF__Shop__Entry__Item_4(ctx: &Context) -> bool {
    ctx.has(&Item::Deku_Basement_Web)
}
pub fn locaccess_KF__Shop__Entry__Item_5(ctx: &Context) -> bool {
    ctx.has(&Item::Biggoron_Sword)
}
pub fn locaccess_KF__Shop__Entry__Item_6(ctx: &Context) -> bool {
    ctx.has(&Item::Nayrus_Love)
}
pub fn locaccess_KF__Shop__Entry__Item_7(ctx: &Context) -> bool {
    ctx.has(&Item::Buy_Deku_Nut_5)
}
pub fn locaccess_KF__Shop__Entry__Item_8(ctx: &Context) -> bool {
    ctx.has(&Item::Triforce_Piece)
}
pub fn locaccess_Kak__Spider_House__Entry__Skulls_10(ctx: &Context) -> bool {
    ctx.has(&Item::Deku_Basement_Block)
}
#[derive(Copy, Clone)]
struct Exit {
    id: ExitId,
    time: i8,
    dest: SpotId,
    price: Currency,

    loc_id: LocationId,
    item: Item,
    canonical: CanonId,
    item_time: i8,

    access_rule: fn(&Context) -> bool,
}

impl world::Accessible for Exit {
    type Context = Context;
    fn can_access(&self, ctx: &Context) -> bool {
        ctx.can_afford(&self.price) && (self.access_rule)(ctx)
    }
}

impl world::Exit for Exit {
    type ExitId = ExitId;
    type SpotId = SpotId;

    fn id(&self) -> &ExitId {
        &self.id
    }
    fn dest(&self) -> &SpotId {
        &self.dest
    }
    fn connect(&mut self, dest: &SpotId) {
        self.dest = *dest;
    }
}

impl world::Location for Exit {
    type LocId = LocationId;
    type CanonId = CanonId;

    fn id(&self) -> &LocationId {
        &self.loc_id
    }
    fn item(&self) -> &Item {
        &self.item
    }

    fn canon_id(&self) -> &CanonId {
        &self.canonical
    }
}

#[derive(Copy, Clone)]
struct Action {
    id: ActionId,
    access_rule: fn(&Context) -> bool,
    activate: fn(&mut Context),
    time: i8,
}

impl world::Accessible for Action {
    type Context = Context;
    fn can_access(&self, ctx: &Context) -> bool {
        (self.access_rule)(ctx)
    }
}
impl world::Action for Action {
    type ActionId = ActionId;
    fn id(&self) -> &ActionId {
        &self.id
    }
}

#[derive(Copy, Clone)]
struct Spot<'a> {
    id: SpotId,
    // we can hold slices here to the real things held in World
    locations: &'a [Location],
    exits: &'a [Exit],
    actions: &'a [Action],
}

impl<'a> world::Spot for Spot<'a> {
    type SpotId = SpotId;
    type Location = Location;
    type Exit = Exit;
    type Action = Action;

    fn id(&self) -> &SpotId {
        &self.id
    }
    fn locations(&self) -> &'a [Location] {
        &self.locations
    }
    fn exits(&self) -> &'a [Exit] {
        &self.exits
    }
    fn actions(&self) -> &'a [Action] {
        &self.actions
    }
}

#[derive(Clone)]
struct World<'a> {
    // These are arrays that group the items together by their parent.
    // Using EnumMap for this ONLY WORKS if the keys are properly ordered to group
    // nearby things together.
    // For entrance rando, we would need to have a layer of indirection:
    // list_index: EnumMap<EnumType, usize>,
    // list: EnumArray<ObjType>,
    locations: EnumMap<LocationId, Location>,
    exits: EnumMap<ExitId, Exit>,
    actions: EnumMap<ActionId, Action>,
    spots: EnumMap<SpotId, Spot<'a>>,
}

impl<'a> world::World for World<'a> {
    type Location = Location;
    type Exit = Exit;
    type Action = Action;
    type Spot = Spot<'a>;

    fn get_location(&self, loc_id: &LocationId) -> &Location {
        &self.locations[*loc_id]
    }
    fn get_exit(&self, ex_id: &ExitId) -> &Exit {
        &self.exits[*ex_id]
    }
    fn get_action(&self, act_id: &ActionId) -> &Action {
        &self.actions[*act_id]
    }
    fn get_spot(&self, sp_id: &SpotId) -> &Spot<'a> {
        &self.spots[*sp_id]
    }
}

pub fn build_locations() -> EnumMap<LocationId, Location> {
    enum_map! {
        LocationId::Deku_Tree__Lobby__Center__Deku_Baba_Sticks => Location {
            id: LocationId::Deku_Tree__Lobby__Center__Deku_Baba_Sticks,
            access_rule: locaccess_Deku_Tree__Lobby__Center__Deku_Baba_Sticks,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::Deku_Tree__Lobby__Center__Deku_Baby_Nuts => Location {
            id: LocationId::Deku_Tree__Lobby__Center__Deku_Baby_Nuts,
            access_rule: locaccess_Deku_Tree__Lobby__Center__Deku_Baby_Nuts,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::Deku_Tree__Lobby__Center__Web => Location {
            id: LocationId::Deku_Tree__Lobby__Center__Web,
            access_rule: locaccess_Deku_Tree__Lobby__Center__Web,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::Deku_Tree__Floor_2__Vines__Map_Chest => Location {
            id: LocationId::Deku_Tree__Floor_2__Vines__Map_Chest,
            access_rule: locaccess_Deku_Tree__Floor_2__Vines__Map_Chest,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::Deku_Tree__Scrub_Room__Entry__Scrub => Location {
            id: LocationId::Deku_Tree__Scrub_Room__Entry__Scrub,
            access_rule: locaccess_Deku_Tree__Scrub_Room__Entry__Scrub,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::Deku_Tree__Slingshot_Room__Slingshot__Chest => Location {
            id: LocationId::Deku_Tree__Slingshot_Room__Slingshot__Chest,
            access_rule: locaccess_Deku_Tree__Slingshot_Room__Slingshot__Chest,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::Deku_Tree__Slingshot_Upper__Ledge__Chest => Location {
            id: LocationId::Deku_Tree__Slingshot_Upper__Ledge__Chest,
            access_rule: locaccess_Deku_Tree__Slingshot_Upper__Ledge__Chest,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::Deku_Tree__Floor_3__Door__Break_Web => Location {
            id: LocationId::Deku_Tree__Floor_3__Door__Break_Web,
            access_rule: locaccess_Deku_Tree__Floor_3__Door__Break_Web,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::Deku_Tree__Compass_Room__Entry__Burn_Web => Location {
            id: LocationId::Deku_Tree__Compass_Room__Entry__Burn_Web,
            access_rule: locaccess_Deku_Tree__Compass_Room__Entry__Burn_Web,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::Deku_Tree__Compass_Room__Compass__Chest => Location {
            id: LocationId::Deku_Tree__Compass_Room__Compass__Chest,
            access_rule: locaccess_Deku_Tree__Compass_Room__Compass__Chest,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::Deku_Tree__Compass_Room__Ledge__Chest => Location {
            id: LocationId::Deku_Tree__Compass_Room__Ledge__Chest,
            access_rule: locaccess_Deku_Tree__Compass_Room__Ledge__Chest,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::Deku_Tree__Compass_Room__Ledge__GS => Location {
            id: LocationId::Deku_Tree__Compass_Room__Ledge__GS,
            access_rule: locaccess_Deku_Tree__Compass_Room__Ledge__GS,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::Deku_Tree__Basement_1__Center__Vines_GS => Location {
            id: LocationId::Deku_Tree__Basement_1__Center__Vines_GS,
            access_rule: locaccess_Deku_Tree__Basement_1__Center__Vines_GS,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::Deku_Tree__Basement_1__Corner__Switch => Location {
            id: LocationId::Deku_Tree__Basement_1__Corner__Switch,
            access_rule: locaccess_Deku_Tree__Basement_1__Corner__Switch,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::Deku_Tree__Basement_1__Corner__Chest => Location {
            id: LocationId::Deku_Tree__Basement_1__Corner__Chest,
            access_rule: locaccess_Deku_Tree__Basement_1__Corner__Chest,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::Deku_Tree__Basement_1__Corner__Gate_GS => Location {
            id: LocationId::Deku_Tree__Basement_1__Corner__Gate_GS,
            access_rule: locaccess_Deku_Tree__Basement_1__Corner__Gate_GS,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::Deku_Tree__Basement_1__Corner__Burn_Basement_Web => Location {
            id: LocationId::Deku_Tree__Basement_1__Corner__Burn_Basement_Web,
            access_rule: locaccess_Deku_Tree__Basement_1__Corner__Burn_Basement_Web,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::Deku_Tree__Back_Room__Northwest__Burn_Web => Location {
            id: LocationId::Deku_Tree__Back_Room__Northwest__Burn_Web,
            access_rule: locaccess_Deku_Tree__Back_Room__Northwest__Burn_Web,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::Deku_Tree__Back_Room__Northwest__Break_Wall => Location {
            id: LocationId::Deku_Tree__Back_Room__Northwest__Break_Wall,
            access_rule: locaccess_Deku_Tree__Back_Room__Northwest__Break_Wall,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::Deku_Tree__Skull_Room__Entry__GS => Location {
            id: LocationId::Deku_Tree__Skull_Room__Entry__GS,
            access_rule: locaccess_Deku_Tree__Skull_Room__Entry__GS,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::Deku_Tree__Basement_Ledge__Block__Push_Block => Location {
            id: LocationId::Deku_Tree__Basement_Ledge__Block__Push_Block,
            access_rule: locaccess_Deku_Tree__Basement_Ledge__Block__Push_Block,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::Deku_Tree__Basement_Ledge__Web__Burn_Web => Location {
            id: LocationId::Deku_Tree__Basement_Ledge__Web__Burn_Web,
            access_rule: locaccess_Deku_Tree__Basement_Ledge__Web__Burn_Web,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::Deku_Tree__Basement_2__Boss_Door__Scrubs => Location {
            id: LocationId::Deku_Tree__Basement_2__Boss_Door__Scrubs,
            access_rule: locaccess_Deku_Tree__Basement_2__Boss_Door__Scrubs,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::Deku_Tree__Boss_Room__Arena__Gohma => Location {
            id: LocationId::Deku_Tree__Boss_Room__Arena__Gohma,
            access_rule: locaccess_Deku_Tree__Boss_Room__Arena__Gohma,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::Deku_Tree__Boss_Room__Arena__Gohma_Quick_Kill => Location {
            id: LocationId::Deku_Tree__Boss_Room__Arena__Gohma_Quick_Kill,
            access_rule: locaccess_Deku_Tree__Boss_Room__Arena__Gohma_Quick_Kill,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::Deku_Tree__Boss_Room__Arena__Gohma_Heart => Location {
            id: LocationId::Deku_Tree__Boss_Room__Arena__Gohma_Heart,
            access_rule: locaccess_Deku_Tree__Boss_Room__Arena__Gohma_Heart,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::Deku_Tree__Boss_Room__Arena__Blue_Warp => Location {
            id: LocationId::Deku_Tree__Boss_Room__Arena__Blue_Warp,
            access_rule: locaccess_Deku_Tree__Boss_Room__Arena__Blue_Warp,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::KF__Kokiri_Village__Midos_Guardpost__Show_Mido => Location {
            id: LocationId::KF__Kokiri_Village__Midos_Guardpost__Show_Mido,
            access_rule: locaccess_KF__Kokiri_Village__Midos_Guardpost__Show_Mido,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::KF__Boulder_Maze__Reward__Chest => Location {
            id: LocationId::KF__Boulder_Maze__Reward__Chest,
            access_rule: locaccess_KF__Boulder_Maze__Reward__Chest,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::KF__Baba_Corridor__Deku_Babas__Sticks => Location {
            id: LocationId::KF__Baba_Corridor__Deku_Babas__Sticks,
            access_rule: locaccess_KF__Baba_Corridor__Deku_Babas__Sticks,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::KF__Baba_Corridor__Deku_Babas__Nuts => Location {
            id: LocationId::KF__Baba_Corridor__Deku_Babas__Nuts,
            access_rule: locaccess_KF__Baba_Corridor__Deku_Babas__Nuts,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::KF__Outside_Deku_Tree__Left__Gossip_Stone => Location {
            id: LocationId::KF__Outside_Deku_Tree__Left__Gossip_Stone,
            access_rule: locaccess_KF__Outside_Deku_Tree__Left__Gossip_Stone,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::KF__Outside_Deku_Tree__Right__Gossip_Stone => Location {
            id: LocationId::KF__Outside_Deku_Tree__Right__Gossip_Stone,
            access_rule: locaccess_KF__Outside_Deku_Tree__Right__Gossip_Stone,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::KF__Midos_House__Entry__Top_Left_Chest => Location {
            id: LocationId::KF__Midos_House__Entry__Top_Left_Chest,
            access_rule: locaccess_KF__Midos_House__Entry__Top_Left_Chest,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::KF__Midos_House__Entry__Top_Right_Chest => Location {
            id: LocationId::KF__Midos_House__Entry__Top_Right_Chest,
            access_rule: locaccess_KF__Midos_House__Entry__Top_Right_Chest,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::KF__Midos_House__Entry__Bottom_Left_Chest => Location {
            id: LocationId::KF__Midos_House__Entry__Bottom_Left_Chest,
            access_rule: locaccess_KF__Midos_House__Entry__Bottom_Left_Chest,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::KF__Midos_House__Entry__Bottom_Right_Chest => Location {
            id: LocationId::KF__Midos_House__Entry__Bottom_Right_Chest,
            access_rule: locaccess_KF__Midos_House__Entry__Bottom_Right_Chest,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::KF__Shop__Entry__Blue_Rupee => Location {
            id: LocationId::KF__Shop__Entry__Blue_Rupee,
            access_rule: locaccess_KF__Shop__Entry__Blue_Rupee,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::KF__Shop__Entry__Item_1 => Location {
            id: LocationId::KF__Shop__Entry__Item_1,
            access_rule: locaccess_KF__Shop__Entry__Item_1,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::KF__Shop__Entry__Item_2 => Location {
            id: LocationId::KF__Shop__Entry__Item_2,
            access_rule: locaccess_KF__Shop__Entry__Item_2,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::KF__Shop__Entry__Item_3 => Location {
            id: LocationId::KF__Shop__Entry__Item_3,
            access_rule: locaccess_KF__Shop__Entry__Item_3,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::KF__Shop__Entry__Item_4 => Location {
            id: LocationId::KF__Shop__Entry__Item_4,
            access_rule: locaccess_KF__Shop__Entry__Item_4,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::KF__Shop__Entry__Item_5 => Location {
            id: LocationId::KF__Shop__Entry__Item_5,
            access_rule: locaccess_KF__Shop__Entry__Item_5,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::KF__Shop__Entry__Item_6 => Location {
            id: LocationId::KF__Shop__Entry__Item_6,
            access_rule: locaccess_KF__Shop__Entry__Item_6,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::KF__Shop__Entry__Item_7 => Location {
            id: LocationId::KF__Shop__Entry__Item_7,
            access_rule: locaccess_KF__Shop__Entry__Item_7,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::KF__Shop__Entry__Item_8 => Location {
            id: LocationId::KF__Shop__Entry__Item_8,
            access_rule: locaccess_KF__Shop__Entry__Item_8,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
        LocationId::Kak__Spider_House__Entry__Skulls_10 => Location {
            id: LocationId::Kak__Spider_House__Entry__Skulls_10,
            access_rule: locaccess_Kak__Spider_House__Entry__Skulls_10,
            canonical: CanonId::None,
            item: Item::None,
            price: Currency::Rupees(0),
            time: 1,
        },
    }
}
