//! AUTOGENERATED FOR sample - DO NOT MODIFY
//!
//! Graph definitions.

#![allow(non_camel_case_types)]

use std::fmt;

#[derive(Debug, PartialEq, Eq, Copy, Clone, enum_map::Enum)]
pub enum Region {
    Deku_Tree,
    KF,
    Kak,
}
impl fmt::Display for Region {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            Region::Deku_Tree => write!(f, "{}", "Deku Tree"),
            Region::KF => write!(f, "{}", "Kokiri Forest"),
            Region::Kak => write!(f, "{}", "Kakariko Village"),
        }
    }
}

#[derive(Debug, PartialEq, Eq, Copy, Clone, enum_map::Enum)]
pub enum Area {
    Deku_Tree__Lobby,
    Deku_Tree__Floor_2,
    Deku_Tree__Scrub_Room,
    Deku_Tree__Slingshot_Room,
    Deku_Tree__Slingshot_Upper,
    Deku_Tree__Floor_3,
    Deku_Tree__Compass_Room,
    Deku_Tree__Basement_1,
    Deku_Tree__Back_Room,
    Deku_Tree__Skull_Room,
    Deku_Tree__Basement_Ledge,
    Deku_Tree__Basement_2,
    Deku_Tree__Boss_Room,
    KF__Links_House,
    KF__Kokiri_Village,
    KF__Boulder_Maze,
    KF__Baba_Corridor,
    KF__Outside_Deku_Tree,
    KF__Midos_House,
    KF__Knowitall_House,
    KF__Shop,
    Kak__Spider_House,
}
impl fmt::Display for Area {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            Area::Deku_Tree__Lobby => write!(f, "{}", "Deku Tree > Lobby"),
            Area::Deku_Tree__Floor_2 => write!(f, "{}", "Deku Tree > Floor 2"),
            Area::Deku_Tree__Scrub_Room => write!(f, "{}", "Deku Tree > Scrub Room"),
            Area::Deku_Tree__Slingshot_Room => write!(f, "{}", "Deku Tree > Slingshot Room"),
            Area::Deku_Tree__Slingshot_Upper => write!(f, "{}", "Deku Tree > Slingshot Upper"),
            Area::Deku_Tree__Floor_3 => write!(f, "{}", "Deku Tree > Floor 3"),
            Area::Deku_Tree__Compass_Room => write!(f, "{}", "Deku Tree > Compass Room"),
            Area::Deku_Tree__Basement_1 => write!(f, "{}", "Deku Tree > Basement 1"),
            Area::Deku_Tree__Back_Room => write!(f, "{}", "Deku Tree > Back Room"),
            Area::Deku_Tree__Skull_Room => write!(f, "{}", "Deku Tree > Skull Room"),
            Area::Deku_Tree__Basement_Ledge => write!(f, "{}", "Deku Tree > Basement Ledge"),
            Area::Deku_Tree__Basement_2 => write!(f, "{}", "Deku Tree > Basement 2"),
            Area::Deku_Tree__Boss_Room => write!(f, "{}", "Deku Tree > Boss Room"),
            Area::KF__Links_House => write!(f, "{}", "KF > Link's House"),
            Area::KF__Kokiri_Village => write!(f, "{}", "KF > Kokiri Village"),
            Area::KF__Boulder_Maze => write!(f, "{}", "KF > Boulder Maze"),
            Area::KF__Baba_Corridor => write!(f, "{}", "KF > Baba Corridor"),
            Area::KF__Outside_Deku_Tree => write!(f, "{}", "KF > Outside Deku Tree"),
            Area::KF__Midos_House => write!(f, "{}", "KF > Mido's House"),
            Area::KF__Knowitall_House => write!(f, "{}", "KF > Know-it-all House"),
            Area::KF__Shop => write!(f, "{}", "KF > Shop"),
            Area::Kak__Spider_House => write!(f, "{}", "Kak > Spider House"),
        }
    }
}

#[derive(Debug, PartialEq, Eq, Copy, Clone, enum_map::Enum)]
pub enum Spot {
    Deku_Tree__Lobby__Entry,
    Deku_Tree__Lobby__Center,
    Deku_Tree__Lobby__Vines,
    Deku_Tree__Floor_2__Lower,
    Deku_Tree__Floor_2__Vines,
    Deku_Tree__Floor_2__Slingshot_Door,
    Deku_Tree__Scrub_Room__Entry,
    Deku_Tree__Scrub_Room__Rear,
    Deku_Tree__Slingshot_Room__Entry,
    Deku_Tree__Slingshot_Room__Slingshot,
    Deku_Tree__Slingshot_Upper__Ledge,
    Deku_Tree__Floor_3__Climb,
    Deku_Tree__Floor_3__Door,
    Deku_Tree__Compass_Room__Entry,
    Deku_Tree__Compass_Room__Compass,
    Deku_Tree__Compass_Room__Ledge,
    Deku_Tree__Basement_1__Center,
    Deku_Tree__Basement_1__Corner,
    Deku_Tree__Basement_1__South_Door,
    Deku_Tree__Back_Room__South,
    Deku_Tree__Back_Room__Northwest,
    Deku_Tree__Back_Room__East,
    Deku_Tree__Skull_Room__Entry,
    Deku_Tree__Basement_Ledge__Block,
    Deku_Tree__Basement_Ledge__Web,
    Deku_Tree__Basement_2__Pool,
    Deku_Tree__Basement_2__Boss_Door,
    Deku_Tree__Boss_Room__Entry,
    Deku_Tree__Boss_Room__Arena,
    KF__Links_House__Start_Point,
    KF__Links_House__Entry,
    KF__Kokiri_Village__Links_Porch,
    KF__Kokiri_Village__Midos_Porch,
    KF__Kokiri_Village__Knowitall_Porch,
    KF__Kokiri_Village__Training_Center,
    KF__Kokiri_Village__Shop_Porch,
    KF__Kokiri_Village__Sarias_Porch,
    KF__Kokiri_Village__Midos_Guardpost,
    KF__Boulder_Maze__Entry,
    KF__Boulder_Maze__Reward,
    KF__Baba_Corridor__Village_Side,
    KF__Baba_Corridor__Deku_Babas,
    KF__Baba_Corridor__Tree_Side,
    KF__Outside_Deku_Tree__Entry,
    KF__Outside_Deku_Tree__Left,
    KF__Outside_Deku_Tree__Right,
    KF__Outside_Deku_Tree__Mouth,
    KF__Midos_House__Entry,
    KF__Knowitall_House__Entry,
    KF__Shop__Entry,
    Kak__Spider_House__Entry,
}
impl fmt::Display for Spot {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            Spot::Deku_Tree__Lobby__Entry => write!(f, "{}", "Deku Tree > Lobby > Entry"),
            Spot::Deku_Tree__Lobby__Center => write!(f, "{}", "Deku Tree > Lobby > Center"),
            Spot::Deku_Tree__Lobby__Vines => write!(f, "{}", "Deku Tree > Lobby > Vines"),
            Spot::Deku_Tree__Floor_2__Lower => write!(f, "{}", "Deku Tree > Floor 2 > Lower"),
            Spot::Deku_Tree__Floor_2__Vines => write!(f, "{}", "Deku Tree > Floor 2 > Vines"),
            Spot::Deku_Tree__Floor_2__Slingshot_Door => {
                write!(f, "{}", "Deku Tree > Floor 2 > Slingshot Door")
            }
            Spot::Deku_Tree__Scrub_Room__Entry => write!(f, "{}", "Deku Tree > Scrub Room > Entry"),
            Spot::Deku_Tree__Scrub_Room__Rear => write!(f, "{}", "Deku Tree > Scrub Room > Rear"),
            Spot::Deku_Tree__Slingshot_Room__Entry => {
                write!(f, "{}", "Deku Tree > Slingshot Room > Entry")
            }
            Spot::Deku_Tree__Slingshot_Room__Slingshot => {
                write!(f, "{}", "Deku Tree > Slingshot Room > Slingshot")
            }
            Spot::Deku_Tree__Slingshot_Upper__Ledge => {
                write!(f, "{}", "Deku Tree > Slingshot Upper > Ledge")
            }
            Spot::Deku_Tree__Floor_3__Climb => write!(f, "{}", "Deku Tree > Floor 3 > Climb"),
            Spot::Deku_Tree__Floor_3__Door => write!(f, "{}", "Deku Tree > Floor 3 > Door"),
            Spot::Deku_Tree__Compass_Room__Entry => {
                write!(f, "{}", "Deku Tree > Compass Room > Entry")
            }
            Spot::Deku_Tree__Compass_Room__Compass => {
                write!(f, "{}", "Deku Tree > Compass Room > Compass")
            }
            Spot::Deku_Tree__Compass_Room__Ledge => {
                write!(f, "{}", "Deku Tree > Compass Room > Ledge")
            }
            Spot::Deku_Tree__Basement_1__Center => {
                write!(f, "{}", "Deku Tree > Basement 1 > Center")
            }
            Spot::Deku_Tree__Basement_1__Corner => {
                write!(f, "{}", "Deku Tree > Basement 1 > Corner")
            }
            Spot::Deku_Tree__Basement_1__South_Door => {
                write!(f, "{}", "Deku Tree > Basement 1 > South Door")
            }
            Spot::Deku_Tree__Back_Room__South => write!(f, "{}", "Deku Tree > Back Room > South"),
            Spot::Deku_Tree__Back_Room__Northwest => {
                write!(f, "{}", "Deku Tree > Back Room > Northwest")
            }
            Spot::Deku_Tree__Back_Room__East => write!(f, "{}", "Deku Tree > Back Room > East"),
            Spot::Deku_Tree__Skull_Room__Entry => write!(f, "{}", "Deku Tree > Skull Room > Entry"),
            Spot::Deku_Tree__Basement_Ledge__Block => {
                write!(f, "{}", "Deku Tree > Basement Ledge > Block")
            }
            Spot::Deku_Tree__Basement_Ledge__Web => {
                write!(f, "{}", "Deku Tree > Basement Ledge > Web")
            }
            Spot::Deku_Tree__Basement_2__Pool => write!(f, "{}", "Deku Tree > Basement 2 > Pool"),
            Spot::Deku_Tree__Basement_2__Boss_Door => {
                write!(f, "{}", "Deku Tree > Basement 2 > Boss Door")
            }
            Spot::Deku_Tree__Boss_Room__Entry => write!(f, "{}", "Deku Tree > Boss Room > Entry"),
            Spot::Deku_Tree__Boss_Room__Arena => write!(f, "{}", "Deku Tree > Boss Room > Arena"),
            Spot::KF__Links_House__Start_Point => {
                write!(f, "{}", "KF > Link's House > Start Point")
            }
            Spot::KF__Links_House__Entry => write!(f, "{}", "KF > Link's House > Entry"),
            Spot::KF__Kokiri_Village__Links_Porch => {
                write!(f, "{}", "KF > Kokiri Village > Link's Porch")
            }
            Spot::KF__Kokiri_Village__Midos_Porch => {
                write!(f, "{}", "KF > Kokiri Village > Mido's Porch")
            }
            Spot::KF__Kokiri_Village__Knowitall_Porch => {
                write!(f, "{}", "KF > Kokiri Village > Know-it-all Porch")
            }
            Spot::KF__Kokiri_Village__Training_Center => {
                write!(f, "{}", "KF > Kokiri Village > Training Center")
            }
            Spot::KF__Kokiri_Village__Shop_Porch => {
                write!(f, "{}", "KF > Kokiri Village > Shop Porch")
            }
            Spot::KF__Kokiri_Village__Sarias_Porch => {
                write!(f, "{}", "KF > Kokiri Village > Saria's Porch")
            }
            Spot::KF__Kokiri_Village__Midos_Guardpost => {
                write!(f, "{}", "KF > Kokiri Village > Mido's Guardpost")
            }
            Spot::KF__Boulder_Maze__Entry => write!(f, "{}", "KF > Boulder Maze > Entry"),
            Spot::KF__Boulder_Maze__Reward => write!(f, "{}", "KF > Boulder Maze > Reward"),
            Spot::KF__Baba_Corridor__Village_Side => {
                write!(f, "{}", "KF > Baba Corridor > Village Side")
            }
            Spot::KF__Baba_Corridor__Deku_Babas => {
                write!(f, "{}", "KF > Baba Corridor > Deku Babas")
            }
            Spot::KF__Baba_Corridor__Tree_Side => write!(f, "{}", "KF > Baba Corridor > Tree Side"),
            Spot::KF__Outside_Deku_Tree__Entry => write!(f, "{}", "KF > Outside Deku Tree > Entry"),
            Spot::KF__Outside_Deku_Tree__Left => write!(f, "{}", "KF > Outside Deku Tree > Left"),
            Spot::KF__Outside_Deku_Tree__Right => write!(f, "{}", "KF > Outside Deku Tree > Right"),
            Spot::KF__Outside_Deku_Tree__Mouth => write!(f, "{}", "KF > Outside Deku Tree > Mouth"),
            Spot::KF__Midos_House__Entry => write!(f, "{}", "KF > Mido's House > Entry"),
            Spot::KF__Knowitall_House__Entry => write!(f, "{}", "KF > Know-it-all House > Entry"),
            Spot::KF__Shop__Entry => write!(f, "{}", "KF > Shop > Entry"),
            Spot::Kak__Spider_House__Entry => write!(f, "{}", "Kak > Spider House > Entry"),
        }
    }
}

#[derive(Debug, PartialEq, Eq, Copy, Clone, enum_map::Enum)]
pub enum Location {
    Deku_Tree__Lobby__Center__Deku_Baba_Sticks,
    Deku_Tree__Lobby__Center__Deku_Baby_Nuts,
    Deku_Tree__Lobby__Center__Web,
    Deku_Tree__Floor_2__Vines__Map_Chest,
    Deku_Tree__Scrub_Room__Entry__Scrub,
    Deku_Tree__Slingshot_Room__Slingshot__Chest,
    Deku_Tree__Slingshot_Upper__Ledge__Chest,
    Deku_Tree__Compass_Room__Compass__Chest,
    Deku_Tree__Compass_Room__Ledge__Chest,
    Deku_Tree__Compass_Room__Ledge__GS,
    Deku_Tree__Basement_1__Center__Vines_GS,
    Deku_Tree__Basement_1__Corner__Switch,
    Deku_Tree__Basement_1__Corner__Chest,
    Deku_Tree__Basement_1__Corner__Gate_GS,
    Deku_Tree__Back_Room__Northwest__Burn_Web,
    Deku_Tree__Back_Room__Northwest__Break_Wall,
    Deku_Tree__Skull_Room__Entry__GS,
    Deku_Tree__Basement_Ledge__Block__Push_Block,
    Deku_Tree__Basement_Ledge__Web__Burn_Web,
    Deku_Tree__Basement_2__Boss_Door__Scrubs,
    Deku_Tree__Boss_Room__Arena__Gohma,
    Deku_Tree__Boss_Room__Arena__Gohma_Quick_Kill,
    Deku_Tree__Boss_Room__Arena__Gohma_Heart,
    KF__Kokiri_Village__Midos_Guardpost__Show_Mido,
    KF__Boulder_Maze__Reward__Chest,
    KF__Baba_Corridor__Deku_Babas__Sticks,
    KF__Baba_Corridor__Deku_Babas__Nuts,
    KF__Outside_Deku_Tree__Left__Gossip_Stone,
    KF__Outside_Deku_Tree__Right__Gossip_Stone,
    KF__Midos_House__Entry__Top_Left_Chest,
    KF__Midos_House__Entry__Top_Right_Chest,
    KF__Midos_House__Entry__Bottom_Left_Chest,
    KF__Midos_House__Entry__Bottom_Right_Chest,
    KF__Shop__Entry__Blue_Rupee,
    KF__Shop__Entry__Item_1,
    KF__Shop__Entry__Item_2,
    KF__Shop__Entry__Item_3,
    KF__Shop__Entry__Item_4,
    KF__Shop__Entry__Item_5,
    KF__Shop__Entry__Item_6,
    KF__Shop__Entry__Item_7,
    KF__Shop__Entry__Item_8,
    Kak__Spider_House__Entry__Skulls_10,
}
impl fmt::Display for Location {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            Location::Deku_Tree__Lobby__Center__Deku_Baba_Sticks => {
                write!(f, "{}", "Deku Tree > Lobby > Center Deku Baba Sticks")
            }
            Location::Deku_Tree__Lobby__Center__Deku_Baby_Nuts => {
                write!(f, "{}", "Deku Tree > Lobby > Center Deku Baby Nuts")
            }
            Location::Deku_Tree__Lobby__Center__Web => {
                write!(f, "{}", "Deku Tree > Lobby > Center Web")
            }
            Location::Deku_Tree__Floor_2__Vines__Map_Chest => {
                write!(f, "{}", "Deku Tree > Floor 2 > Vines Map Chest")
            }
            Location::Deku_Tree__Scrub_Room__Entry__Scrub => {
                write!(f, "{}", "Deku Tree > Scrub Room > Entry Scrub")
            }
            Location::Deku_Tree__Slingshot_Room__Slingshot__Chest => {
                write!(f, "{}", "Deku Tree > Slingshot Room > Slingshot Chest")
            }
            Location::Deku_Tree__Slingshot_Upper__Ledge__Chest => {
                write!(f, "{}", "Deku Tree > Slingshot Upper > Ledge Chest")
            }
            Location::Deku_Tree__Compass_Room__Compass__Chest => {
                write!(f, "{}", "Deku Tree > Compass Room > Compass Chest")
            }
            Location::Deku_Tree__Compass_Room__Ledge__Chest => {
                write!(f, "{}", "Deku Tree > Compass Room > Ledge Chest")
            }
            Location::Deku_Tree__Compass_Room__Ledge__GS => {
                write!(f, "{}", "Deku Tree > Compass Room > Ledge GS")
            }
            Location::Deku_Tree__Basement_1__Center__Vines_GS => {
                write!(f, "{}", "Deku Tree > Basement 1 > Center Vines GS")
            }
            Location::Deku_Tree__Basement_1__Corner__Switch => {
                write!(f, "{}", "Deku Tree > Basement 1 > Corner Switch")
            }
            Location::Deku_Tree__Basement_1__Corner__Chest => {
                write!(f, "{}", "Deku Tree > Basement 1 > Corner Chest")
            }
            Location::Deku_Tree__Basement_1__Corner__Gate_GS => {
                write!(f, "{}", "Deku Tree > Basement 1 > Corner Gate GS")
            }
            Location::Deku_Tree__Back_Room__Northwest__Burn_Web => {
                write!(f, "{}", "Deku Tree > Back Room > Northwest Burn Web")
            }
            Location::Deku_Tree__Back_Room__Northwest__Break_Wall => {
                write!(f, "{}", "Deku Tree > Back Room > Northwest Break Wall")
            }
            Location::Deku_Tree__Skull_Room__Entry__GS => {
                write!(f, "{}", "Deku Tree > Skull Room > Entry GS")
            }
            Location::Deku_Tree__Basement_Ledge__Block__Push_Block => {
                write!(f, "{}", "Deku Tree > Basement Ledge > Block Push Block")
            }
            Location::Deku_Tree__Basement_Ledge__Web__Burn_Web => {
                write!(f, "{}", "Deku Tree > Basement Ledge > Web Burn Web")
            }
            Location::Deku_Tree__Basement_2__Boss_Door__Scrubs => {
                write!(f, "{}", "Deku Tree > Basement 2 > Boss Door Scrubs")
            }
            Location::Deku_Tree__Boss_Room__Arena__Gohma => {
                write!(f, "{}", "Deku Tree > Boss Room > Arena Gohma")
            }
            Location::Deku_Tree__Boss_Room__Arena__Gohma_Quick_Kill => {
                write!(f, "{}", "Deku Tree > Boss Room > Arena Gohma Quick Kill")
            }
            Location::Deku_Tree__Boss_Room__Arena__Gohma_Heart => {
                write!(f, "{}", "Deku Tree > Boss Room > Arena Gohma Heart")
            }
            Location::KF__Kokiri_Village__Midos_Guardpost__Show_Mido => {
                write!(f, "{}", "KF > Kokiri Village > Mido's Guardpost Show Mido")
            }
            Location::KF__Boulder_Maze__Reward__Chest => {
                write!(f, "{}", "KF > Boulder Maze > Reward Chest")
            }
            Location::KF__Baba_Corridor__Deku_Babas__Sticks => {
                write!(f, "{}", "KF > Baba Corridor > Deku Babas Sticks")
            }
            Location::KF__Baba_Corridor__Deku_Babas__Nuts => {
                write!(f, "{}", "KF > Baba Corridor > Deku Babas Nuts")
            }
            Location::KF__Outside_Deku_Tree__Left__Gossip_Stone => {
                write!(f, "{}", "KF > Outside Deku Tree > Left Gossip Stone")
            }
            Location::KF__Outside_Deku_Tree__Right__Gossip_Stone => {
                write!(f, "{}", "KF > Outside Deku Tree > Right Gossip Stone")
            }
            Location::KF__Midos_House__Entry__Top_Left_Chest => {
                write!(f, "{}", "KF > Mido's House > Entry Top Left Chest")
            }
            Location::KF__Midos_House__Entry__Top_Right_Chest => {
                write!(f, "{}", "KF > Mido's House > Entry Top Right Chest")
            }
            Location::KF__Midos_House__Entry__Bottom_Left_Chest => {
                write!(f, "{}", "KF > Mido's House > Entry Bottom Left Chest")
            }
            Location::KF__Midos_House__Entry__Bottom_Right_Chest => {
                write!(f, "{}", "KF > Mido's House > Entry Bottom Right Chest")
            }
            Location::KF__Shop__Entry__Blue_Rupee => {
                write!(f, "{}", "KF > Shop > Entry Blue Rupee")
            }
            Location::KF__Shop__Entry__Item_1 => write!(f, "{}", "KF > Shop > Entry Item 1"),
            Location::KF__Shop__Entry__Item_2 => write!(f, "{}", "KF > Shop > Entry Item 2"),
            Location::KF__Shop__Entry__Item_3 => write!(f, "{}", "KF > Shop > Entry Item 3"),
            Location::KF__Shop__Entry__Item_4 => write!(f, "{}", "KF > Shop > Entry Item 4"),
            Location::KF__Shop__Entry__Item_5 => write!(f, "{}", "KF > Shop > Entry Item 5"),
            Location::KF__Shop__Entry__Item_6 => write!(f, "{}", "KF > Shop > Entry Item 6"),
            Location::KF__Shop__Entry__Item_7 => write!(f, "{}", "KF > Shop > Entry Item 7"),
            Location::KF__Shop__Entry__Item_8 => write!(f, "{}", "KF > Shop > Entry Item 8"),
            Location::Kak__Spider_House__Entry__Skulls_10 => {
                write!(f, "{}", "Kak > Spider House > Entry Skulls 10")
            }
        }
    }
}

#[derive(Debug, PartialEq, Eq, Copy, Clone, enum_map::Enum)]
pub enum Exit {
    Deku_Tree__Lobby__Center__ex__Basement_1__Center_1,
    Deku_Tree__Lobby__Center__ex__Basement_Ledge__Block_1,
    Deku_Tree__Lobby__Vines__ex__Floor_2__Lower_1,
    Deku_Tree__Floor_2__Lower__ex__Lobby__Vines_1,
    Deku_Tree__Floor_2__Vines__ex__Floor_3__Climb_1,
    Deku_Tree__Floor_2__Vines__ex__Floor_3__Climb_2,
    Deku_Tree__Floor_2__Vines__ex__Lobby__Vines_1,
    Deku_Tree__Floor_2__Vines__ex__Lobby__Entry_1,
    Deku_Tree__Floor_2__Slingshot_Door__ex__Scrub_Room__Entry_1,
    Deku_Tree__Floor_2__Slingshot_Door__ex__Lobby__Entry_1,
    Deku_Tree__Scrub_Room__Rear__ex__Slingshot_Room__Entry_1,
    Deku_Tree__Slingshot_Room__Entry__ex__Scrub_Room__Rear_1,
    Deku_Tree__Slingshot_Room__Slingshot__ex__Slingshot_Upper__Ledge_1,
    Deku_Tree__Slingshot_Upper__Ledge__ex__Slingshot_Room__Slingshot_1,
    Deku_Tree__Floor_3__Door__ex__Compass_Room__Entry_1,
    Deku_Tree__Floor_3__Door__ex__Lobby__Center_1,
    Deku_Tree__Floor_3__Door__Break_Web,
    Deku_Tree__Compass_Room__Entry__ex__Floor_3__Door_1,
    Deku_Tree__Compass_Room__Entry__Burn_Web,
    Deku_Tree__Compass_Room__Compass__ex__Ledge_1,
    Deku_Tree__Compass_Room__Ledge__ex__Compass_1,
    Deku_Tree__Basement_1__Center__ex__Lobby__Center_1,
    Deku_Tree__Basement_1__Corner__ex__Basement_Ledge__Block_1,
    Deku_Tree__Basement_1__Corner__Burn_Basement_Web,
    Deku_Tree__Basement_1__South_Door__ex__Back_Room__South_1,
    Deku_Tree__Back_Room__Northwest__ex__Skull_Room__Entry_1,
    Deku_Tree__Back_Room__East__ex__Basement_Ledge__Web_1,
    Deku_Tree__Skull_Room__Entry__ex__Back_Room__Northweest_1,
    Deku_Tree__Basement_Ledge__Block__ex__Basement_1__Corner_1,
    Deku_Tree__Basement_Ledge__Web__ex__Basement_2__Pool_1,
    Deku_Tree__Basement_2__Pool__ex__Basement_Ledge__Web_1,
    Deku_Tree__Basement_2__Boss_Door__ex__Boss_Room__Entry_1,
    Deku_Tree__Boss_Room__Arena__Blue_Warp,
    KF__Links_House__Entry__ex__Kokiri_Village__Links_Porch_1,
    KF__Kokiri_Village__Links_Porch__ex__Links_House__Entry_1,
    KF__Kokiri_Village__Links_Porch__ex__Knowitall_Porch_1,
    KF__Kokiri_Village__Links_Porch__ex__Training_Center_1,
    KF__Kokiri_Village__Links_Porch__ex__Midos_Guardpost_1,
    KF__Kokiri_Village__Midos_Porch__ex__Midos_House__Entry_1,
    KF__Kokiri_Village__Knowitall_Porch__ex__Knowitall_House__Entry_1,
    KF__Kokiri_Village__Training_Center__ex__Boulder_Maze__Entry_1,
    KF__Kokiri_Village__Shop_Porch__ex__Shop__Entry_1,
    KF__Kokiri_Village__Sarias_Porch__ex__Kak__Spider_House__Entry_1,
    KF__Kokiri_Village__Midos_Guardpost__ex__Baba_Corridor__Village_Side_1,
    KF__Boulder_Maze__Entry__ex__Kokiri_Village__Training_Center_1,
    KF__Baba_Corridor__Village_Side__ex__Kokiri_Village__Midos_Guardpost_1,
    KF__Baba_Corridor__Tree_Side__ex__Outside_Deku_Tree__Entry_1,
    KF__Outside_Deku_Tree__Entry__ex__Baba_Corridor__Tree_Side_1,
    KF__Outside_Deku_Tree__Mouth__ex__Deku_Tree__Lobby__Entry_1,
    KF__Midos_House__Entry__ex__Kokiri_Village__Midos_Porch_1,
    KF__Knowitall_House__Entry__ex__Kokiri_Village__Knowitall_Porch_1,
    KF__Shop__Entry__ex__Kokiri_Village__Shop_Porch_1,
    Kak__Spider_House__Entry__ex__KF__Kokiri_Village__Sarias_Porch_1,
}
impl fmt::Display for Exit {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            Exit::Deku_Tree__Lobby__Center__ex__Basement_1__Center_1 => write!(
                f,
                "{}",
                "Deku Tree > Lobby > Center ==> Basement 1 > Center (1)"
            ),
            Exit::Deku_Tree__Lobby__Center__ex__Basement_Ledge__Block_1 => write!(
                f,
                "{}",
                "Deku Tree > Lobby > Center ==> Basement Ledge > Block (1)"
            ),
            Exit::Deku_Tree__Lobby__Vines__ex__Floor_2__Lower_1 => {
                write!(f, "{}", "Deku Tree > Lobby > Vines ==> Floor 2 > Lower (1)")
            }
            Exit::Deku_Tree__Floor_2__Lower__ex__Lobby__Vines_1 => {
                write!(f, "{}", "Deku Tree > Floor 2 > Lower ==> Lobby > Vines (1)")
            }
            Exit::Deku_Tree__Floor_2__Vines__ex__Floor_3__Climb_1 => write!(
                f,
                "{}",
                "Deku Tree > Floor 2 > Vines ==> Floor 3 > Climb (1)"
            ),
            Exit::Deku_Tree__Floor_2__Vines__ex__Floor_3__Climb_2 => write!(
                f,
                "{}",
                "Deku Tree > Floor 2 > Vines ==> Floor 3 > Climb (2)"
            ),
            Exit::Deku_Tree__Floor_2__Vines__ex__Lobby__Vines_1 => {
                write!(f, "{}", "Deku Tree > Floor 2 > Vines ==> Lobby > Vines (1)")
            }
            Exit::Deku_Tree__Floor_2__Vines__ex__Lobby__Entry_1 => {
                write!(f, "{}", "Deku Tree > Floor 2 > Vines ==> Lobby > Entry (1)")
            }
            Exit::Deku_Tree__Floor_2__Slingshot_Door__ex__Scrub_Room__Entry_1 => write!(
                f,
                "{}",
                "Deku Tree > Floor 2 > Slingshot Door ==> Scrub Room > Entry (1)"
            ),
            Exit::Deku_Tree__Floor_2__Slingshot_Door__ex__Lobby__Entry_1 => write!(
                f,
                "{}",
                "Deku Tree > Floor 2 > Slingshot Door ==> Lobby > Entry (1)"
            ),
            Exit::Deku_Tree__Scrub_Room__Rear__ex__Slingshot_Room__Entry_1 => write!(
                f,
                "{}",
                "Deku Tree > Scrub Room > Rear ==> Slingshot Room > Entry (1)"
            ),
            Exit::Deku_Tree__Slingshot_Room__Entry__ex__Scrub_Room__Rear_1 => write!(
                f,
                "{}",
                "Deku Tree > Slingshot Room > Entry ==> Scrub Room > Rear (1)"
            ),
            Exit::Deku_Tree__Slingshot_Room__Slingshot__ex__Slingshot_Upper__Ledge_1 => write!(
                f,
                "{}",
                "Deku Tree > Slingshot Room > Slingshot ==> Slingshot Upper > Ledge (1)"
            ),
            Exit::Deku_Tree__Slingshot_Upper__Ledge__ex__Slingshot_Room__Slingshot_1 => write!(
                f,
                "{}",
                "Deku Tree > Slingshot Upper > Ledge ==> Slingshot Room > Slingshot (1)"
            ),
            Exit::Deku_Tree__Floor_3__Door__ex__Compass_Room__Entry_1 => write!(
                f,
                "{}",
                "Deku Tree > Floor 3 > Door ==> Compass Room > Entry (1)"
            ),
            Exit::Deku_Tree__Floor_3__Door__ex__Lobby__Center_1 => {
                write!(f, "{}", "Deku Tree > Floor 3 > Door ==> Lobby > Center (1)")
            }
            Exit::Deku_Tree__Floor_3__Door__Break_Web => {
                write!(f, "{}", "Deku Tree > Floor 3 > Door Break Web")
            }
            Exit::Deku_Tree__Compass_Room__Entry__ex__Floor_3__Door_1 => write!(
                f,
                "{}",
                "Deku Tree > Compass Room > Entry ==> Floor 3 > Door (1)"
            ),
            Exit::Deku_Tree__Compass_Room__Entry__Burn_Web => {
                write!(f, "{}", "Deku Tree > Compass Room > Entry Burn Web")
            }
            Exit::Deku_Tree__Compass_Room__Compass__ex__Ledge_1 => {
                write!(f, "{}", "Deku Tree > Compass Room > Compass ==> Ledge (1)")
            }
            Exit::Deku_Tree__Compass_Room__Ledge__ex__Compass_1 => {
                write!(f, "{}", "Deku Tree > Compass Room > Ledge ==> Compass (1)")
            }
            Exit::Deku_Tree__Basement_1__Center__ex__Lobby__Center_1 => write!(
                f,
                "{}",
                "Deku Tree > Basement 1 > Center ==> Lobby > Center (1)"
            ),
            Exit::Deku_Tree__Basement_1__Corner__ex__Basement_Ledge__Block_1 => write!(
                f,
                "{}",
                "Deku Tree > Basement 1 > Corner ==> Basement Ledge > Block (1)"
            ),
            Exit::Deku_Tree__Basement_1__Corner__Burn_Basement_Web => {
                write!(f, "{}", "Deku Tree > Basement 1 > Corner Burn Basement Web")
            }
            Exit::Deku_Tree__Basement_1__South_Door__ex__Back_Room__South_1 => write!(
                f,
                "{}",
                "Deku Tree > Basement 1 > South Door ==> Back Room > South (1)"
            ),
            Exit::Deku_Tree__Back_Room__Northwest__ex__Skull_Room__Entry_1 => write!(
                f,
                "{}",
                "Deku Tree > Back Room > Northwest ==> Skull Room > Entry (1)"
            ),
            Exit::Deku_Tree__Back_Room__East__ex__Basement_Ledge__Web_1 => write!(
                f,
                "{}",
                "Deku Tree > Back Room > East ==> Basement Ledge > Web (1)"
            ),
            Exit::Deku_Tree__Skull_Room__Entry__ex__Back_Room__Northweest_1 => write!(
                f,
                "{}",
                "Deku Tree > Skull Room > Entry ==> Back Room > Northweest (1)"
            ),
            Exit::Deku_Tree__Basement_Ledge__Block__ex__Basement_1__Corner_1 => write!(
                f,
                "{}",
                "Deku Tree > Basement Ledge > Block ==> Basement 1 > Corner (1)"
            ),
            Exit::Deku_Tree__Basement_Ledge__Web__ex__Basement_2__Pool_1 => write!(
                f,
                "{}",
                "Deku Tree > Basement Ledge > Web ==> Basement 2 > Pool (1)"
            ),
            Exit::Deku_Tree__Basement_2__Pool__ex__Basement_Ledge__Web_1 => write!(
                f,
                "{}",
                "Deku Tree > Basement 2 > Pool ==> Basement Ledge > Web (1)"
            ),
            Exit::Deku_Tree__Basement_2__Boss_Door__ex__Boss_Room__Entry_1 => write!(
                f,
                "{}",
                "Deku Tree > Basement 2 > Boss Door ==> Boss Room > Entry (1)"
            ),
            Exit::Deku_Tree__Boss_Room__Arena__Blue_Warp => {
                write!(f, "{}", "Deku Tree > Boss Room > Arena Blue Warp")
            }
            Exit::KF__Links_House__Entry__ex__Kokiri_Village__Links_Porch_1 => write!(
                f,
                "{}",
                "KF > Link's House > Entry ==> Kokiri Village > Link's Porch (1)"
            ),
            Exit::KF__Kokiri_Village__Links_Porch__ex__Links_House__Entry_1 => write!(
                f,
                "{}",
                "KF > Kokiri Village > Link's Porch ==> Link's House > Entry (1)"
            ),
            Exit::KF__Kokiri_Village__Links_Porch__ex__Knowitall_Porch_1 => write!(
                f,
                "{}",
                "KF > Kokiri Village > Link's Porch ==> Know-it-all Porch (1)"
            ),
            Exit::KF__Kokiri_Village__Links_Porch__ex__Training_Center_1 => write!(
                f,
                "{}",
                "KF > Kokiri Village > Link's Porch ==> Training Center (1)"
            ),
            Exit::KF__Kokiri_Village__Links_Porch__ex__Midos_Guardpost_1 => write!(
                f,
                "{}",
                "KF > Kokiri Village > Link's Porch ==> Mido's Guardpost (1)"
            ),
            Exit::KF__Kokiri_Village__Midos_Porch__ex__Midos_House__Entry_1 => write!(
                f,
                "{}",
                "KF > Kokiri Village > Mido's Porch ==> Mido's House > Entry (1)"
            ),
            Exit::KF__Kokiri_Village__Knowitall_Porch__ex__Knowitall_House__Entry_1 => write!(
                f,
                "{}",
                "KF > Kokiri Village > Know-it-all Porch ==> Know-it-all House > Entry (1)"
            ),
            Exit::KF__Kokiri_Village__Training_Center__ex__Boulder_Maze__Entry_1 => write!(
                f,
                "{}",
                "KF > Kokiri Village > Training Center ==> Boulder Maze > Entry (1)"
            ),
            Exit::KF__Kokiri_Village__Shop_Porch__ex__Shop__Entry_1 => write!(
                f,
                "{}",
                "KF > Kokiri Village > Shop Porch ==> Shop > Entry (1)"
            ),
            Exit::KF__Kokiri_Village__Sarias_Porch__ex__Kak__Spider_House__Entry_1 => write!(
                f,
                "{}",
                "KF > Kokiri Village > Saria's Porch ==> Kak > Spider House > Entry (1)"
            ),
            Exit::KF__Kokiri_Village__Midos_Guardpost__ex__Baba_Corridor__Village_Side_1 => write!(
                f,
                "{}",
                "KF > Kokiri Village > Mido's Guardpost ==> Baba Corridor > Village Side (1)"
            ),
            Exit::KF__Boulder_Maze__Entry__ex__Kokiri_Village__Training_Center_1 => write!(
                f,
                "{}",
                "KF > Boulder Maze > Entry ==> Kokiri Village > Training Center (1)"
            ),
            Exit::KF__Baba_Corridor__Village_Side__ex__Kokiri_Village__Midos_Guardpost_1 => write!(
                f,
                "{}",
                "KF > Baba Corridor > Village Side ==> Kokiri Village > Mido's Guardpost (1)"
            ),
            Exit::KF__Baba_Corridor__Tree_Side__ex__Outside_Deku_Tree__Entry_1 => write!(
                f,
                "{}",
                "KF > Baba Corridor > Tree Side ==> Outside Deku Tree > Entry (1)"
            ),
            Exit::KF__Outside_Deku_Tree__Entry__ex__Baba_Corridor__Tree_Side_1 => write!(
                f,
                "{}",
                "KF > Outside Deku Tree > Entry ==> Baba Corridor > Tree Side (1)"
            ),
            Exit::KF__Outside_Deku_Tree__Mouth__ex__Deku_Tree__Lobby__Entry_1 => write!(
                f,
                "{}",
                "KF > Outside Deku Tree > Mouth ==> Deku Tree > Lobby > Entry (1)"
            ),
            Exit::KF__Midos_House__Entry__ex__Kokiri_Village__Midos_Porch_1 => write!(
                f,
                "{}",
                "KF > Mido's House > Entry ==> Kokiri Village > Mido's Porch (1)"
            ),
            Exit::KF__Knowitall_House__Entry__ex__Kokiri_Village__Knowitall_Porch_1 => write!(
                f,
                "{}",
                "KF > Know-it-all House > Entry ==> Kokiri Village > Know-it-all Porch (1)"
            ),
            Exit::KF__Shop__Entry__ex__Kokiri_Village__Shop_Porch_1 => write!(
                f,
                "{}",
                "KF > Shop > Entry ==> Kokiri Village > Shop Porch (1)"
            ),
            Exit::Kak__Spider_House__Entry__ex__KF__Kokiri_Village__Sarias_Porch_1 => write!(
                f,
                "{}",
                "Kak > Spider House > Entry ==> KF > Kokiri Village > Saria's Porch (1)"
            ),
        }
    }
}

#[derive(Debug, PartialEq, Eq, Copy, Clone, enum_map::Enum)]
pub enum Action {
    Deku_Tree__Compass_Room__Entry__Light_Torch,
}
impl fmt::Display for Action {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            Action::Deku_Tree__Compass_Room__Entry__Light_Torch => {
                write!(f, "{}", "Deku Tree > Compass Room > Entry Light Torch")
            }
        }
    }
}

#[derive(Debug, PartialEq, Eq, Copy, Clone, enum_map::Enum, Default)]
pub enum Canon {
    #[default]
    None,
    Deku_Lobby_Web,
    Deku_Basement_Web,
}
impl fmt::Display for Canon {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            Canon::None => write!(f, "{}", "None"),
            Canon::Deku_Lobby_Web => write!(f, "{}", "Deku_Lobby_Web"),
            Canon::Deku_Basement_Web => write!(f, "{}", "Deku_Basement_Web"),
        }
    }
}
