//! AUTOGENERATED FOR sample - DO NOT MODIFY
//!
//! Context (game state).

use std::fmt;

#[derive(Debug, PartialEq, Eq, Copy, Clone, Default, Hash, Ord, PartialOrd)]
pub enum Currency {
    #[default]
    Free,
    Rupees(i32),
}

impl analyzer::world::Id for Currency {}

impl fmt::Display for Currency {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Free => write!(f, "Free"),
            Self::Rupees(i) => write!(f, "{}:{}", "Rupees", i),
        }
    }
}
