//! AUTOGENERATED FOR sample - MODIFICATIONS WILL BE LOST

#![allow(non_camel_case_types)]

use serde::{Serialize, Deserialize};
use std::fmt;

#[derive(Debug, PartialEq, Eq, Copy, Clone, Default, Hash, Ord, PartialOrd, Serialize, Deserialize)]
pub enum Currency {
    #[default] Free,
    Rupees(i32),
}

impl analyzer::world::Id for Currency {}

impl fmt::Display for Currency {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Free => write!(f, "Free"),
            Self::Rupees(i) => write!(f, "{}:{}", "Rupees", i),
        }
    }
}

impl std::str::FromStr for Currency {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        if s == "Free" {
            return Ok(Currency::Free);
        } else if let Some(t) = s.strip_suffix(")") {
            if let Some((price, val)) = t.split_once("(") {
                match price {
                    "Rupees" => return Ok(Currency::Rupees(
                        i32::from_str(val).map_err(|e| format!("{}", e))?)),
                    _ => (),
                }
            }
        }
        Err(format!("Could not recognize as a Currency: {}", s))
    }
}