# AUTOGENERATED FOR Axiom Verge 2 - MODIFICATIONS WILL BE LOST
# Requires graphviz (for neato), GraphicsMagick (for gm), m4 (for scripting), and bash (for shell redirection)

if [[ $1 ]]; then
    FILE=$(realpath $1);
else
    FILE=full_graph.m4;
fi
(
cd "$( dirname -- "${BASH_SOURCE[0]}" )";
PNG=$(basename -- ${FILE%.m4}).png;
echo "Generating graph..." &&
neato -Tpng -o $PNG <(m4 $FILE) &&
echo "Merging graph with map..." &&
gm composite $PNG AV2-World-50%.png ${PNG%.png}-map.png;
echo "Graph created at $(realpath ${PNG%.png}-map.png)";
)