//! AUTOGENERATED FOR Axiom Verge 2 - MODIFICATIONS WILL BE LOST

#![allow(non_camel_case_types)]

use std::fmt;

#[derive(Debug, PartialEq, Eq, Copy, Clone, Hash, Ord, PartialOrd, enum_map::Enum, Default)]
pub enum Item {
    #[default]
    None,
    Amagi_Dragon_Eye_Passage,
    Amagi_Stronghold_Boulder_1,
    Amagi_Stronghold_Boulder_2,
    Amagi_Stronghold_Boulder_And_Wall_2,
    Amagi_Stronghold_Left_Wall,
    Amagi_Stronghold_Wall_1,
    Amagi_Stronghold_Wall_2,
    Amagi_Stronghold_Wall_And_Boulder_1,
    Amagi_West_Lake_Surface_Wall,
    Amashilama,
    Anuman,
    Apocalypse_Bomb,
    Boomerang,
    Bronze_Axe,
    Companies_Layoff,
    Compass,
    Dear_Ernest,
    Defeat_Ebih_Alu,
    Defeat_MUS_A_M20,
    Drone_Hover,
    Drone_Melee_Damage,
    Drone_Melee_Speed,
    Escape,
    Flask,
    Health,
    Health_Fragment,
    Health_Node,
    Health_Upgrade,
    Heretics_Tablet,
    Ice_Axe,
    Infect,
    Infection_Range,
    Infection_Speed,
    Ledge_Grab,
    Melee_Charge,
    Melee_Damage,
    Melee_Speed,
    Mist_Upgrade,
    Nanite_Mist,
    Nano_Points,
    Notes_2053_02_27,
    Ranged_Damage,
    Ranged_Speed,
    Record_Losses,
    Remote_Drone,
    Shockwave,
    Slingshot_Hook,
    Station_Power,
    Switch_36_11,
    Switch_40_12,
    Terminal_Breakthrough_1,
    Under_Siege,
    Underwater_Movement,
    Wall_Climb,
}
impl fmt::Display for Item {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            Item::None => write!(f, "{}", "None"),
            Item::Amagi_Dragon_Eye_Passage => write!(f, "{}", "Amagi_Dragon_Eye_Passage"),
            Item::Amagi_Stronghold_Boulder_1 => write!(f, "{}", "Amagi_Stronghold_Boulder_1"),
            Item::Amagi_Stronghold_Boulder_2 => write!(f, "{}", "Amagi_Stronghold_Boulder_2"),
            Item::Amagi_Stronghold_Boulder_And_Wall_2 => {
                write!(f, "{}", "Amagi_Stronghold_Boulder_And_Wall_2")
            }
            Item::Amagi_Stronghold_Left_Wall => write!(f, "{}", "Amagi_Stronghold_Left_Wall"),
            Item::Amagi_Stronghold_Wall_1 => write!(f, "{}", "Amagi_Stronghold_Wall_1"),
            Item::Amagi_Stronghold_Wall_2 => write!(f, "{}", "Amagi_Stronghold_Wall_2"),
            Item::Amagi_Stronghold_Wall_And_Boulder_1 => {
                write!(f, "{}", "Amagi_Stronghold_Wall_And_Boulder_1")
            }
            Item::Amagi_West_Lake_Surface_Wall => write!(f, "{}", "Amagi_West_Lake_Surface_Wall"),
            Item::Amashilama => write!(f, "{}", "Amashilama"),
            Item::Anuman => write!(f, "{}", "Anuman"),
            Item::Apocalypse_Bomb => write!(f, "{}", "Apocalypse_Bomb"),
            Item::Boomerang => write!(f, "{}", "Boomerang"),
            Item::Bronze_Axe => write!(f, "{}", "Bronze_Axe"),
            Item::Companies_Layoff => write!(f, "{}", "Companies_Layoff"),
            Item::Compass => write!(f, "{}", "Compass"),
            Item::Dear_Ernest => write!(f, "{}", "Dear_Ernest"),
            Item::Defeat_Ebih_Alu => write!(f, "{}", "Defeat_Ebih_Alu"),
            Item::Defeat_MUS_A_M20 => write!(f, "{}", "Defeat_MUS_A_M20"),
            Item::Drone_Hover => write!(f, "{}", "Drone_Hover"),
            Item::Drone_Melee_Damage => write!(f, "{}", "Drone_Melee_Damage"),
            Item::Drone_Melee_Speed => write!(f, "{}", "Drone_Melee_Speed"),
            Item::Escape => write!(f, "{}", "Escape"),
            Item::Flask => write!(f, "{}", "Flask"),
            Item::Health => write!(f, "{}", "Health"),
            Item::Health_Fragment => write!(f, "{}", "Health_Fragment"),
            Item::Health_Node => write!(f, "{}", "Health_Node"),
            Item::Health_Upgrade => write!(f, "{}", "Health_Upgrade"),
            Item::Heretics_Tablet => write!(f, "{}", "Heretics_Tablet"),
            Item::Ice_Axe => write!(f, "{}", "Ice_Axe"),
            Item::Infect => write!(f, "{}", "Infect"),
            Item::Infection_Range => write!(f, "{}", "Infection_Range"),
            Item::Infection_Speed => write!(f, "{}", "Infection_Speed"),
            Item::Ledge_Grab => write!(f, "{}", "Ledge_Grab"),
            Item::Melee_Charge => write!(f, "{}", "Melee_Charge"),
            Item::Melee_Damage => write!(f, "{}", "Melee_Damage"),
            Item::Melee_Speed => write!(f, "{}", "Melee_Speed"),
            Item::Mist_Upgrade => write!(f, "{}", "Mist_Upgrade"),
            Item::Nanite_Mist => write!(f, "{}", "Nanite_Mist"),
            Item::Nano_Points => write!(f, "{}", "Nano_Points"),
            Item::Notes_2053_02_27 => write!(f, "{}", "Notes_2053_02_27"),
            Item::Ranged_Damage => write!(f, "{}", "Ranged_Damage"),
            Item::Ranged_Speed => write!(f, "{}", "Ranged_Speed"),
            Item::Record_Losses => write!(f, "{}", "Record_Losses"),
            Item::Remote_Drone => write!(f, "{}", "Remote_Drone"),
            Item::Shockwave => write!(f, "{}", "Shockwave"),
            Item::Slingshot_Hook => write!(f, "{}", "Slingshot_Hook"),
            Item::Station_Power => write!(f, "{}", "Station_Power"),
            Item::Switch_36_11 => write!(f, "{}", "Switch_36_11"),
            Item::Switch_40_12 => write!(f, "{}", "Switch_40_12"),
            Item::Terminal_Breakthrough_1 => write!(f, "{}", "Terminal_Breakthrough_1"),
            Item::Under_Siege => write!(f, "{}", "Under_Siege"),
            Item::Underwater_Movement => write!(f, "{}", "Underwater_Movement"),
            Item::Wall_Climb => write!(f, "{}", "Wall_Climb"),
        }
    }
}
impl analyzer::world::Id for Item {}
impl std::str::FromStr for Item {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Amagi_Dragon_Eye_Passage" => Ok(Item::Amagi_Dragon_Eye_Passage),
            "Amagi_Stronghold_Boulder_1" => Ok(Item::Amagi_Stronghold_Boulder_1),
            "Amagi_Stronghold_Boulder_2" => Ok(Item::Amagi_Stronghold_Boulder_2),
            "Amagi_Stronghold_Boulder_And_Wall_2" => Ok(Item::Amagi_Stronghold_Boulder_And_Wall_2),
            "Amagi_Stronghold_Left_Wall" => Ok(Item::Amagi_Stronghold_Left_Wall),
            "Amagi_Stronghold_Wall_1" => Ok(Item::Amagi_Stronghold_Wall_1),
            "Amagi_Stronghold_Wall_2" => Ok(Item::Amagi_Stronghold_Wall_2),
            "Amagi_Stronghold_Wall_And_Boulder_1" => Ok(Item::Amagi_Stronghold_Wall_And_Boulder_1),
            "Amagi_West_Lake_Surface_Wall" => Ok(Item::Amagi_West_Lake_Surface_Wall),
            "Amashilama" => Ok(Item::Amashilama),
            "Anuman" => Ok(Item::Anuman),
            "Apocalypse_Bomb" => Ok(Item::Apocalypse_Bomb),
            "Boomerang" => Ok(Item::Boomerang),
            "Bronze_Axe" => Ok(Item::Bronze_Axe),
            "Companies_Layoff" => Ok(Item::Companies_Layoff),
            "Compass" => Ok(Item::Compass),
            "Dear_Ernest" => Ok(Item::Dear_Ernest),
            "Defeat_Ebih_Alu" => Ok(Item::Defeat_Ebih_Alu),
            "Defeat_MUS_A_M20" => Ok(Item::Defeat_MUS_A_M20),
            "Drone_Hover" => Ok(Item::Drone_Hover),
            "Drone_Melee_Damage" => Ok(Item::Drone_Melee_Damage),
            "Drone_Melee_Speed" => Ok(Item::Drone_Melee_Speed),
            "Escape" => Ok(Item::Escape),
            "Flask" => Ok(Item::Flask),
            "Health" => Ok(Item::Health),
            "Health_Fragment" => Ok(Item::Health_Fragment),
            "Health_Node" => Ok(Item::Health_Node),
            "Health_Upgrade" => Ok(Item::Health_Upgrade),
            "Heretics_Tablet" => Ok(Item::Heretics_Tablet),
            "Ice_Axe" => Ok(Item::Ice_Axe),
            "Infect" => Ok(Item::Infect),
            "Infection_Range" => Ok(Item::Infection_Range),
            "Infection_Speed" => Ok(Item::Infection_Speed),
            "Ledge_Grab" => Ok(Item::Ledge_Grab),
            "Melee_Charge" => Ok(Item::Melee_Charge),
            "Melee_Damage" => Ok(Item::Melee_Damage),
            "Melee_Speed" => Ok(Item::Melee_Speed),
            "Mist_Upgrade" => Ok(Item::Mist_Upgrade),
            "Nanite_Mist" => Ok(Item::Nanite_Mist),
            "Nano_Points" => Ok(Item::Nano_Points),
            "Notes_2053_02_27" => Ok(Item::Notes_2053_02_27),
            "Ranged_Damage" => Ok(Item::Ranged_Damage),
            "Ranged_Speed" => Ok(Item::Ranged_Speed),
            "Record_Losses" => Ok(Item::Record_Losses),
            "Remote_Drone" => Ok(Item::Remote_Drone),
            "Shockwave" => Ok(Item::Shockwave),
            "Slingshot_Hook" => Ok(Item::Slingshot_Hook),
            "Station_Power" => Ok(Item::Station_Power),
            "Switch_36_11" => Ok(Item::Switch_36_11),
            "Switch_40_12" => Ok(Item::Switch_40_12),
            "Terminal_Breakthrough_1" => Ok(Item::Terminal_Breakthrough_1),
            "Under_Siege" => Ok(Item::Under_Siege),
            "Underwater_Movement" => Ok(Item::Underwater_Movement),
            "Wall_Climb" => Ok(Item::Wall_Climb),
            _ => Err(format!("Could not recognize as a Item: {}", s)),
        }
    }
}

pub fn unused_item(id: Item) -> bool {
    match id {
        Item::None => true,
        Item::Amagi_Stronghold_Left_Wall
        | Item::Bronze_Axe
        | Item::Companies_Layoff
        | Item::Compass
        | Item::Dear_Ernest
        | Item::Escape
        | Item::Health
        | Item::Health_Fragment
        | Item::Heretics_Tablet
        | Item::Melee_Charge
        | Item::Notes_2053_02_27
        | Item::Record_Losses
        | Item::Terminal_Breakthrough_1
        | Item::Under_Siege => true,
        _ => false,
    }
}
