//! AUTOGENERATED FOR Axiom Verge 2 - MODIFICATIONS WILL BE LOST

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(unused)]

use crate::context::Context;
use crate::graph::SpotId;
use crate::rules;
use analyzer::context::Ctx;

#[derive(Debug, PartialEq, Eq, Copy, Clone, Default)]
enum Movement {
    #[default]
    Default,
}

fn has_movement(ctx: &Context, m: Movement, spot: SpotId) -> bool {
    match m {
        Movement::Default => true,
    }
}

pub fn local_travel_time(ctx: &Context, src: SpotId, dest: SpotId) -> i32 {
    match (src, dest) {
        (SpotId::Antarctica__West__Helipad, SpotId::Antarctica__West__Shed_Entry) => 4385,
        (SpotId::Antarctica__West__Helipad, SpotId::Antarctica__West__Boxes) => 5263,
        (SpotId::Antarctica__West__Shed_Entry, SpotId::Antarctica__West__Helipad) => 4385,
        (SpotId::Antarctica__West__Shed_Entry, SpotId::Antarctica__West__Boxes) => 9649,
        (SpotId::Antarctica__West__Boxes, SpotId::Antarctica__West__Helipad) => 5263,
        (SpotId::Antarctica__West__Boxes, SpotId::Antarctica__West__Shed_Entry) => 9649,
        (
            SpotId::Antarctica__Building_1W__West_Entry,
            SpotId::Antarctica__Building_1W__Connector,
        ) => 2631,
        (
            SpotId::Antarctica__Building_1W__Connector,
            SpotId::Antarctica__Building_1W__West_Entry,
        ) => 2631,
        (
            SpotId::Antarctica__Building_1E__Connector,
            SpotId::Antarctica__Building_1E__East_Entry,
        ) => 2631,
        (
            SpotId::Antarctica__Building_1E__East_Entry,
            SpotId::Antarctica__Building_1E__Connector,
        ) => 2631,
        (SpotId::Antarctica__East__Building_1_Entry, SpotId::Antarctica__East__Save_Point) => 877,
        (
            SpotId::Antarctica__East__Building_1_Entry,
            SpotId::Antarctica__East__Building_2_Entry,
        ) => 2631,
        (SpotId::Antarctica__East__Save_Point, SpotId::Antarctica__East__Building_1_Entry) => 877,
        (SpotId::Antarctica__East__Save_Point, SpotId::Antarctica__East__Building_2_Entry) => 1754,
        (
            SpotId::Antarctica__East__Building_2_Entry,
            SpotId::Antarctica__East__Building_1_Entry,
        ) => 2631,
        (SpotId::Antarctica__East__Building_2_Entry, SpotId::Antarctica__East__Save_Point) => 1754,
        (SpotId::Antarctica__Building_2U__Stairs, SpotId::Antarctica__Building_2U__Door) => 3508,
        (SpotId::Antarctica__Building_2U__Door, SpotId::Antarctica__Building_2U__Stairs) => 3508,
        (SpotId::Antarctica__Power_Room__Entry, SpotId::Antarctica__Power_Room__Switch) => 1403,
        (SpotId::Antarctica__Power_Room__Switch, SpotId::Antarctica__Power_Room__Entry) => 1403,
        (
            SpotId::Antarctica__Freight_Elevator__Left,
            SpotId::Antarctica__Freight_Elevator__Controls,
        ) => 2105,
        (
            SpotId::Antarctica__Freight_Elevator__Controls,
            SpotId::Antarctica__Freight_Elevator__Left,
        ) => 2105,
        _ => -1,
    }
}
