//! AUTOGENERATED FOR Axiom Verge 2 - MODIFICATIONS WILL BE LOST

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(unused)]

use crate::context::*;
use crate::graph::*;
use crate::items::Item;
use crate::prices::Currency;
use crate::*;
use analyzer::context::Ctx;
use analyzer::world;

pub fn access_default(_ctx: &Context) -> bool {
    true
}

pub fn access_amashilama(ctx: &Context) -> bool {
    // Amashilama
    ctx.has(Item::Amashilama)
}
pub fn access_amashilama__notes_2053_02_27(ctx: &Context) -> bool {
    // Amashilama && Notes_2053_02_27
    (ctx.has(Item::Amashilama) && ctx.has(Item::Notes_2053_02_27))
}
pub fn access_amashilama_and_mode__drone(ctx: &Context) -> bool {
    // Amashilama and ^mode != 'drone'
    (ctx.has(Item::Amashilama) && ctx.mode() != enums::Mode::Drone)
}
pub fn access_apocalypse_bomb(ctx: &Context) -> bool {
    // Apocalypse_Bomb
    ctx.has(Item::Apocalypse_Bomb)
}
pub fn access_break_box(ctx: &Context) -> bool {
    // $break_box
    helper__break_box!(ctx)
}
pub fn access_mist(ctx: &Context) -> bool {
    // Mist
    ctx.has(Item::Mist)
}
pub fn access_mode__drone(ctx: &Context) -> bool {
    // ^mode == 'drone'
    ctx.mode() == enums::Mode::Drone
}
pub fn access_placeholder(ctx: &Context) -> bool {
    // Placeholder
    ctx.has(Item::Placeholder)
}
pub fn access_station_power(ctx: &Context) -> bool {
    // Station_Power
    ctx.has(Item::Station_Power)
}
pub fn access_within_antarctica(ctx: &Context) -> bool {
    // WITHIN `Antarctica`
    (match get_region(ctx.position()) {
        RegionId::Antarctica => true,
        _ => false,
    })
}
pub fn action_energy__1(ctx: &mut Context) {
    // ^energy += 1
    ctx.energy += 1;
}
pub fn action_has_effect_energy__1(ctx: &Context) -> bool {
    0 != 1
}
pub fn action_position__glacier__revival__save_point_save__glacier__revival__save_point(
    ctx: &mut Context,
) {
    // ^position = `Glacier > Revival > Save Point`; ^save = `Glacier > Revival > Save Point`
    ctx.position = SpotId::Glacier__Revival__Save_Point;
    ctx.save = SpotId::Glacier__Revival__Save_Point;
}
pub fn action_has_effect_position__glacier__revival__save_point_save__glacier__revival__save_point(
    ctx: &Context,
) -> bool {
    ctx.position != SpotId::Glacier__Revival__Save_Point
        || ctx.save != SpotId::Glacier__Revival__Save_Point
}
pub fn action_save__position(ctx: &mut Context) {
    // ^save = ^position
    ctx.save = ctx.position();
}
pub fn action_has_effect_save__position(ctx: &Context) -> bool {
    ctx.save != ctx.position()
}
